-- Policies, tables a–m. Introspected from production 16 Aug 2026.
-- Depends on the helper functions in 04: is_sakred_admin(), can_see_channel().
CREATE POLICY applications_admin ON public.applications AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY sakred_applications_insert ON public.applications AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
CREATE POLICY sakred_applications_select ON public.applications AS PERMISSIVE FOR SELECT TO public USING (is_sakred_admin());
CREATE POLICY body_measurements_no_client ON public.body_measurements AS PERMISSIVE FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
CREATE POLICY sakred_bookings_admin_select ON public.booking_requests AS PERMISSIVE FOR SELECT TO public USING (is_sakred_admin());
CREATE POLICY sakred_bookings_admin_update ON public.booking_requests AS PERMISSIVE FOR UPDATE TO public USING (is_sakred_admin());
CREATE POLICY sakred_bookings_insert ON public.booking_requests AS PERMISSIVE FOR INSERT TO public WITH CHECK (((auth.uid())::text = (user_id)::text));
CREATE POLICY sakred_bookings_select ON public.booking_requests AS PERMISSIVE FOR SELECT TO public USING (((auth.uid())::text = (user_id)::text));
CREATE POLICY sakred_bookings_update ON public.booking_requests AS PERMISSIVE FOR UPDATE TO public USING (((auth.uid())::text = (user_id)::text));
CREATE POLICY centre_habits_select ON public.centre_habits AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY centre_habits_write ON public.centre_habits AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY centre_routines_select ON public.centre_routines AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY centre_routines_write ON public.centre_routines AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY channel_members_no_client ON public.channel_members AS PERMISSIVE FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
CREATE POLICY channels_select ON public.channels AS PERMISSIVE FOR SELECT TO public USING ((can_see_channel((auth.uid())::text, id) OR is_sakred_admin()));
CREATE POLICY channels_write ON public.channels AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY sakred_coaching_msgs_admin_update ON public.coaching_messages AS PERMISSIVE FOR UPDATE TO public USING (true);
CREATE POLICY sakred_coaching_msgs_insert ON public.coaching_messages AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
CREATE POLICY sakred_coaching_msgs_select ON public.coaching_messages AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY cohort_attendance_admin ON public.cohort_attendance AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY cohort_attendance_own ON public.cohort_attendance AS PERMISSIVE FOR SELECT TO public USING ((((user_id)::text = (auth.uid())::text) OR is_sakred_admin()));
CREATE POLICY cohort_members_admin ON public.cohort_members AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY cohort_members_apply ON public.cohort_members AS PERMISSIVE FOR INSERT TO public WITH CHECK ((((user_id)::text = (auth.uid())::text) OR is_sakred_admin()));
CREATE POLICY cohort_members_own ON public.cohort_members AS PERMISSIVE FOR SELECT TO public USING ((((user_id)::text = (auth.uid())::text) OR is_sakred_admin()));
CREATE POLICY cohort_sessions_admin ON public.cohort_sessions AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY cohort_sessions_select ON public.cohort_sessions AS PERMISSIVE FOR SELECT TO public USING ((is_sakred_admin() OR (EXISTS ( SELECT 1
   FROM cohort_members m
  WHERE ((m.cohort_id = cohort_sessions.cohort_id) AND ((m.user_id)::text = (auth.uid())::text) AND (m.status = 'confirmed'::text))))));
CREATE POLICY cohorts_select ON public.cohorts AS PERMISSIVE FOR SELECT TO public USING (((status <> 'draft'::text) OR is_sakred_admin()));
CREATE POLICY cohorts_write ON public.cohorts AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY community_messages_admin ON public.community_messages AS PERMISSIVE FOR DELETE TO public USING (is_sakred_admin());
CREATE POLICY community_messages_insert ON public.community_messages AS PERMISSIVE FOR INSERT TO public WITH CHECK ((((user_id)::text = (auth.uid())::text) AND can_see_channel((auth.uid())::text, channel_id) AND (NOT (EXISTS ( SELECT 1
   FROM channels c
  WHERE ((c.id = community_messages.channel_id) AND c.is_read_only))))));
CREATE POLICY community_messages_own ON public.community_messages AS PERMISSIVE FOR UPDATE TO public USING ((((user_id)::text = (auth.uid())::text) OR is_sakred_admin()));
CREATE POLICY community_messages_select ON public.community_messages AS PERMISSIVE FOR SELECT TO public USING ((can_see_channel((auth.uid())::text, channel_id) OR is_sakred_admin()));
CREATE POLICY content_reports_no_client ON public.content_reports AS PERMISSIVE FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
CREATE POLICY daily_intentions_own ON public.daily_intentions AS PERMISSIVE FOR ALL TO public USING (((user_id)::text = (auth.uid())::text)) WITH CHECK (((user_id)::text = (auth.uid())::text));
CREATE POLICY daily_intentions_read ON public.daily_intentions AS PERMISSIVE FOR SELECT TO public USING ((((user_id)::text = (auth.uid())::text) OR is_sakred_admin()));
CREATE POLICY daily_notes_admin ON public.daily_notes AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY daily_notes_own ON public.daily_notes AS PERMISSIVE FOR SELECT TO public USING ((((user_id)::text = (auth.uid())::text) OR is_sakred_admin()));
CREATE POLICY ebook_entitlements_admin ON public.ebook_entitlements AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY ebook_entitlements_own ON public.ebook_entitlements AS PERMISSIVE FOR SELECT TO public USING ((((user_id)::text = (auth.uid())::text) OR is_sakred_admin()));
CREATE POLICY ebook_progress_own ON public.ebook_progress AS PERMISSIVE FOR ALL TO public USING (((user_id)::text = (auth.uid())::text)) WITH CHECK (((user_id)::text = (auth.uid())::text));
CREATE POLICY ebook_sections_admin ON public.ebook_sections AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY ebooks_select ON public.ebooks AS PERMISSIVE FOR SELECT TO public USING ((is_published OR is_sakred_admin()));
CREATE POLICY ebooks_write ON public.ebooks AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY energy_centres_select ON public.energy_centres AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY energy_centres_write ON public.energy_centres AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY events_read_own ON public.events AS PERMISSIVE FOR SELECT TO public USING (((user_id)::text = (auth.uid())::text));
CREATE POLICY sakred_exec_applications_insert ON public.executive_applications AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
CREATE POLICY sakred_exec_applications_select ON public.executive_applications AS PERMISSIVE FOR SELECT TO public USING (is_sakred_admin());
CREATE POLICY sakred_exec_applications_update ON public.executive_applications AS PERMISSIVE FOR UPDATE TO public USING (is_sakred_admin());
CREATE POLICY exercises_read ON public.exercises AS PERMISSIVE FOR SELECT TO authenticated USING (is_active);
CREATE POLICY frequencies_select ON public.frequencies AS PERMISSIVE FOR SELECT TO public USING ((is_active OR is_sakred_admin()));
CREATE POLICY frequencies_write ON public.frequencies AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY habit_entries_service ON public.habit_entries AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY habit_exercises_read ON public.habit_exercises AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY habit_products_select ON public.habit_products AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY habit_products_write ON public.habit_products AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY habit_proposals_service ON public.habit_proposals AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY habit_relations_service ON public.habit_relations AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY sakred_hra_delete ON public.habit_routine_assignments AS PERMISSIVE FOR DELETE TO public USING (is_sakred_admin());
CREATE POLICY sakred_hra_insert ON public.habit_routine_assignments AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_sakred_admin());
CREATE POLICY sakred_hra_select ON public.habit_routine_assignments AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY sakred_hra_update ON public.habit_routine_assignments AS PERMISSIVE FOR UPDATE TO public USING (is_sakred_admin());
CREATE POLICY sakred_habits_insert ON public.habits AS PERMISSIVE FOR INSERT TO public WITH CHECK (((auth.uid())::text = user_id));
CREATE POLICY sakred_habits_select ON public.habits AS PERMISSIVE FOR SELECT TO public USING (((auth.uid())::text = user_id));
CREATE POLICY sakred_habits_update ON public.habits AS PERMISSIVE FOR UPDATE TO public USING (((auth.uid())::text = user_id));
CREATE POLICY hosts_read ON public.hosts AS PERMISSIVE FOR SELECT TO public USING (is_active);
CREATE POLICY login_attempts_no_client_access ON public.login_attempts AS PERMISSIVE FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
CREATE POLICY sakred_mc_categories_delete ON public.masterclass_categories AS PERMISSIVE FOR DELETE TO public USING (is_sakred_admin());
CREATE POLICY sakred_mc_categories_insert ON public.masterclass_categories AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_sakred_admin());
CREATE POLICY sakred_mc_categories_select ON public.masterclass_categories AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY sakred_mc_categories_update ON public.masterclass_categories AS PERMISSIVE FOR UPDATE TO public USING (is_sakred_admin());
CREATE POLICY sakred_mc_videos_delete ON public.masterclass_videos AS PERMISSIVE FOR DELETE TO public USING (is_sakred_admin());
CREATE POLICY sakred_mc_videos_insert ON public.masterclass_videos AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_sakred_admin());
CREATE POLICY sakred_mc_videos_select ON public.masterclass_videos AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY sakred_mc_videos_update ON public.masterclass_videos AS PERMISSIVE FOR UPDATE TO public USING (is_sakred_admin());
CREATE POLICY member_build_profile_service ON public.member_build_profile AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY membership_tiers_select ON public.membership_tiers AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY membership_tiers_write ON public.membership_tiers AS PERMISSIVE FOR ALL TO public USING (is_sakred_admin()) WITH CHECK (is_sakred_admin());
CREATE POLICY message_reactions_own ON public.message_reactions AS PERMISSIVE FOR ALL TO public USING ((((user_id)::text = (auth.uid())::text) OR is_sakred_admin())) WITH CHECK (((user_id)::text = (auth.uid())::text));
