-- ═══════════════════════════════════════════════════════════════════════════
-- The movement catalogue — 658 movements, 40 categories
-- ═══════════════════════════════════════════════════════════════════════════
--
-- GENERATED from shared/data/exerciseCatalogue.ts by script/seed-exercises.ts.
-- Edit the data module, not this file — the rules about which categories take
-- load and how each is tracked live there, and hand-editing here is how a foam
-- roll ends up logged in kilograms.
--
-- Idempotent. `owner_user_id` is deliberately never touched, so re-running
-- cannot disturb a movement a member added for themselves.
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO exercises
  (id, name, category, pattern, equipment, tracking_type, takes_load, unilateral,
   bodyweight_factor, tracks_one_rep_max, aliases, sort_order)
VALUES
  ('barbell-bench-press', 'Barbell Bench Press', 'chest', 'push', 'barbell', 'reps', true, false, 0, true, '{"bench","bench press","bb bench"}'::text[], 10),
  ('incline-barbell-bench-press', 'Incline Barbell Bench Press', 'chest', 'push', 'barbell', 'reps', true, false, 0, true, '{"incline bench"}'::text[], 20),
  ('decline-barbell-bench-press', 'Decline Barbell Bench Press', 'chest', 'push', 'barbell', 'reps', true, false, 0, true, NULL, 30),
  ('dumbbell-bench-press', 'Dumbbell Bench Press', 'chest', 'push', 'dumbbell', 'reps', true, false, 0, false, '{"db bench"}'::text[], 40),
  ('incline-dumbbell-press', 'Incline Dumbbell Press', 'chest', 'push', 'dumbbell', 'reps', true, false, 0, false, NULL, 50),
  ('decline-dumbbell-press', 'Decline Dumbbell Press', 'chest', 'push', 'dumbbell', 'reps', true, false, 0, false, NULL, 60),
  ('dumbbell-squeeze-press', 'Dumbbell Squeeze Press', 'chest', 'push', 'dumbbell', 'reps', true, false, 0, false, NULL, 70),
  ('machine-chest-press', 'Machine Chest Press', 'chest', 'push', 'machine', 'reps', true, false, 0, false, NULL, 80),
  ('incline-machine-chest-press', 'Incline Machine Chest Press', 'chest', 'push', 'machine', 'reps', true, false, 0, false, NULL, 90),
  ('plate-loaded-chest-press', 'Plate-Loaded Chest Press', 'chest', 'push', 'machine', 'reps', true, false, 0, false, NULL, 100),
  ('smith-machine-bench-press', 'Smith Machine Bench Press', 'chest', 'push', 'machine', 'reps', true, false, 0, false, NULL, 110),
  ('smith-machine-incline-press', 'Smith Machine Incline Press', 'chest', 'push', 'machine', 'reps', true, false, 0, false, NULL, 120),
  ('cable-chest-press', 'Cable Chest Press', 'chest', 'push', 'cable', 'reps', true, false, 0, false, NULL, 130),
  ('cable-fly', 'Cable Fly', 'chest', 'push', 'cable', 'reps', true, false, 0, false, '{"fly","flye"}'::text[], 140),
  ('low-to-high-cable-fly', 'Low-to-High Cable Fly', 'chest', 'push', 'cable', 'reps', true, false, 0, false, NULL, 150),
  ('high-to-low-cable-fly', 'High-to-Low Cable Fly', 'chest', 'push', 'cable', 'reps', true, false, 0, false, NULL, 160),
  ('pec-deck', 'Pec Deck', 'chest', 'push', 'machine', 'reps', true, false, 0, false, '{"machine fly","pec dec"}'::text[], 170),
  ('push-up', 'Push-Up', 'chest', 'push', 'bodyweight', 'reps', false, false, 0.64, false, '{"pushup","press up"}'::text[], 180),
  ('weighted-push-up', 'Weighted Push-Up', 'chest', 'push', 'bodyweight', 'reps', true, false, 0.64, false, NULL, 190),
  ('dip-chest-emphasis', 'Dip — Chest Emphasis', 'chest', 'push', 'bodyweight', 'reps', true, false, 1, false, '{"chest dip"}'::text[], 200),
  ('conventional-deadlift', 'Conventional Deadlift', 'back', 'hinge', 'barbell', 'reps', true, false, 0, true, '{"deadlift","dl"}'::text[], 210),
  ('rack-pull', 'Rack Pull', 'back', 'hinge', 'barbell', 'reps', true, false, 0, true, NULL, 220),
  ('barbell-row', 'Barbell Row', 'back', 'pull', 'barbell', 'reps', true, false, 0, false, '{"bent over row","bb row"}'::text[], 230),
  ('pendlay-row', 'Pendlay Row', 'back', 'pull', 'barbell', 'reps', true, false, 0, false, NULL, 240),
  ('t-bar-row', 'T-Bar Row', 'back', 'pull', 'machine', 'reps', true, false, 0, false, NULL, 250),
  ('chest-supported-t-bar-row', 'Chest-Supported T-Bar Row', 'back', 'pull', 'machine', 'reps', true, false, 0, false, NULL, 260),
  ('dumbbell-row', 'Dumbbell Row', 'back', 'pull', 'dumbbell', 'reps', true, true, 0, false, '{"db row","one arm row"}'::text[], 270),
  ('chest-supported-dumbbell-row', 'Chest-Supported Dumbbell Row', 'back', 'pull', 'dumbbell', 'reps', true, false, 0, false, NULL, 280),
  ('meadows-row', 'Meadows Row', 'back', 'pull', 'barbell', 'reps', true, true, 0, false, NULL, 290),
  ('seal-row', 'Seal Row', 'back', 'pull', 'barbell', 'reps', true, false, 0, false, NULL, 300),
  ('machine-row', 'Machine Row', 'back', 'pull', 'machine', 'reps', true, false, 0, false, NULL, 310),
  ('plate-loaded-row', 'Plate-Loaded Row', 'back', 'pull', 'machine', 'reps', true, false, 0, false, NULL, 320),
  ('iso-lateral-row', 'Iso-Lateral Row', 'back', 'pull', 'machine', 'reps', true, true, 0, false, NULL, 330),
  ('seated-cable-row', 'Seated Cable Row', 'back', 'pull', 'cable', 'reps', true, false, 0, false, '{"cable row"}'::text[], 340),
  ('wide-grip-cable-row', 'Wide-Grip Cable Row', 'back', 'pull', 'cable', 'reps', true, false, 0, false, NULL, 350),
  ('single-arm-cable-row', 'Single-Arm Cable Row', 'back', 'pull', 'cable', 'reps', true, true, 0, false, NULL, 360),
  ('lat-pulldown', 'Lat Pulldown', 'back', 'pull', 'cable', 'reps', true, false, 0, false, '{"pulldown","lats"}'::text[], 370),
  ('neutral-grip-lat-pulldown', 'Neutral-Grip Lat Pulldown', 'back', 'pull', 'cable', 'reps', true, false, 0, false, NULL, 380),
  ('close-grip-lat-pulldown', 'Close-Grip Lat Pulldown', 'back', 'pull', 'cable', 'reps', true, false, 0, false, NULL, 390),
  ('single-arm-lat-pulldown', 'Single-Arm Lat Pulldown', 'back', 'pull', 'cable', 'reps', true, true, 0, false, NULL, 400),
  ('straight-arm-pulldown', 'Straight-Arm Pulldown', 'back', 'pull', 'cable', 'reps', true, false, 0, false, NULL, 410),
  ('machine-pullover', 'Machine Pullover', 'back', 'pull', 'machine', 'reps', true, false, 0, false, NULL, 420),
  ('dumbbell-pullover', 'Dumbbell Pullover', 'back', 'pull', 'dumbbell', 'reps', true, false, 0, false, NULL, 430),
  ('pull-up', 'Pull-Up', 'back', 'pull', 'bodyweight', 'reps', false, false, 1, false, '{"pullup"}'::text[], 440),
  ('chin-up', 'Chin-Up', 'back', 'pull', 'bodyweight', 'reps', false, false, 1, false, '{"chinup"}'::text[], 450),
  ('assisted-pull-up', 'Assisted Pull-Up', 'back', 'pull', 'machine', 'reps', true, false, 1, false, NULL, 460),
  ('weighted-pull-up', 'Weighted Pull-Up', 'back', 'pull', 'bodyweight', 'reps', true, false, 1, false, NULL, 470),
  ('barbell-overhead-press', 'Barbell Overhead Press', 'shoulders', 'push', 'barbell', 'reps', true, false, 0, true, '{"ohp","overhead press","military press"}'::text[], 480),
  ('seated-barbell-shoulder-press', 'Seated Barbell Shoulder Press', 'shoulders', 'push', 'barbell', 'reps', true, false, 0, false, NULL, 490),
  ('dumbbell-shoulder-press', 'Dumbbell Shoulder Press', 'shoulders', 'push', 'dumbbell', 'reps', true, false, 0, false, NULL, 500),
  ('arnold-press', 'Arnold Press', 'shoulders', 'push', 'dumbbell', 'reps', true, false, 0, false, NULL, 510),
  ('machine-shoulder-press', 'Machine Shoulder Press', 'shoulders', 'push', 'machine', 'reps', true, false, 0, false, NULL, 520),
  ('plate-loaded-shoulder-press', 'Plate-Loaded Shoulder Press', 'shoulders', 'push', 'machine', 'reps', true, false, 0, false, NULL, 530),
  ('smith-machine-shoulder-press', 'Smith Machine Shoulder Press', 'shoulders', 'push', 'machine', 'reps', true, false, 0, false, NULL, 540),
  ('dumbbell-lateral-raise', 'Dumbbell Lateral Raise', 'shoulders', 'push', 'dumbbell', 'reps', true, false, 0, false, '{"lat raise","side raise"}'::text[], 550),
  ('seated-lateral-raise', 'Seated Lateral Raise', 'shoulders', 'push', 'dumbbell', 'reps', true, false, 0, false, NULL, 560),
  ('leaning-lateral-raise', 'Leaning Lateral Raise', 'shoulders', 'push', 'dumbbell', 'reps', true, true, 0, false, NULL, 570),
  ('cable-lateral-raise', 'Cable Lateral Raise', 'shoulders', 'push', 'cable', 'reps', true, true, 0, false, NULL, 580),
  ('behind-the-back-cable-lateral-raise', 'Behind-the-Back Cable Lateral Raise', 'shoulders', 'push', 'cable', 'reps', true, true, 0, false, NULL, 590),
  ('machine-lateral-raise', 'Machine Lateral Raise', 'shoulders', 'push', 'machine', 'reps', true, false, 0, false, NULL, 600),
  ('dumbbell-front-raise', 'Dumbbell Front Raise', 'shoulders', 'push', 'dumbbell', 'reps', true, false, 0, false, NULL, 610),
  ('cable-front-raise', 'Cable Front Raise', 'shoulders', 'push', 'cable', 'reps', true, false, 0, false, NULL, 620),
  ('rear-delt-dumbbell-fly', 'Rear-Delt Dumbbell Fly', 'shoulders', 'pull', 'dumbbell', 'reps', true, false, 0, false, '{"rear delt"}'::text[], 630),
  ('reverse-pec-deck', 'Reverse Pec Deck', 'shoulders', 'pull', 'machine', 'reps', true, false, 0, false, NULL, 640),
  ('cable-rear-delt-fly', 'Cable Rear-Delt Fly', 'shoulders', 'pull', 'cable', 'reps', true, false, 0, false, NULL, 650),
  ('face-pull', 'Face Pull', 'shoulders', 'pull', 'cable', 'reps', true, false, 0, false, NULL, 660),
  ('upright-row', 'Upright Row', 'shoulders', 'pull', 'barbell', 'reps', true, false, 0, false, NULL, 670),
  ('barbell-curl', 'Barbell Curl', 'arms', 'pull', 'barbell', 'reps', true, false, 0, false, '{"bb curl","curl"}'::text[], 680),
  ('ez-bar-curl', 'EZ-Bar Curl', 'arms', 'pull', 'barbell', 'reps', true, false, 0, false, NULL, 690),
  ('dumbbell-curl', 'Dumbbell Curl', 'arms', 'pull', 'dumbbell', 'reps', true, false, 0, false, NULL, 700),
  ('alternating-dumbbell-curl', 'Alternating Dumbbell Curl', 'arms', 'pull', 'dumbbell', 'reps', true, true, 0, false, NULL, 710),
  ('incline-dumbbell-curl', 'Incline Dumbbell Curl', 'arms', 'pull', 'dumbbell', 'reps', true, false, 0, false, NULL, 720),
  ('hammer-curl', 'Hammer Curl', 'arms', 'pull', 'dumbbell', 'reps', true, false, 0, false, '{"hammers"}'::text[], 730),
  ('cross-body-hammer-curl', 'Cross-Body Hammer Curl', 'arms', 'pull', 'dumbbell', 'reps', true, true, 0, false, NULL, 740),
  ('preacher-curl', 'Preacher Curl', 'arms', 'pull', 'barbell', 'reps', true, false, 0, false, NULL, 750),
  ('machine-preacher-curl', 'Machine Preacher Curl', 'arms', 'pull', 'machine', 'reps', true, false, 0, false, NULL, 760),
  ('cable-curl', 'Cable Curl', 'arms', 'pull', 'cable', 'reps', true, false, 0, false, NULL, 770),
  ('bayesian-cable-curl', 'Bayesian Cable Curl', 'arms', 'pull', 'cable', 'reps', true, true, 0, false, NULL, 780),
  ('spider-curl', 'Spider Curl', 'arms', 'pull', 'dumbbell', 'reps', true, false, 0, false, NULL, 790),
  ('concentration-curl', 'Concentration Curl', 'arms', 'pull', 'dumbbell', 'reps', true, true, 0, false, NULL, 800),
  ('reverse-curl', 'Reverse Curl', 'arms', 'pull', 'barbell', 'reps', true, false, 0, false, NULL, 810),
  ('zottman-curl', 'Zottman Curl', 'arms', 'pull', 'dumbbell', 'reps', true, false, 0, false, NULL, 820),
  ('wrist-curl', 'Wrist Curl', 'arms', 'pull', 'dumbbell', 'reps', true, false, 0, false, NULL, 830),
  ('reverse-wrist-curl', 'Reverse Wrist Curl', 'arms', 'pull', 'dumbbell', 'reps', true, false, 0, false, NULL, 840),
  ('wrist-roller', 'Wrist Roller', 'arms', 'pull', 'other', 'duration', true, false, 0, false, NULL, 850),
  ('close-grip-bench-press', 'Close-Grip Bench Press', 'arms', 'push', 'barbell', 'reps', true, false, 0, true, '{"cgbp"}'::text[], 860),
  ('skull-crusher', 'Skull Crusher', 'arms', 'push', 'barbell', 'reps', true, false, 0, false, '{"lying triceps extension"}'::text[], 870),
  ('ez-bar-skull-crusher', 'EZ-Bar Skull Crusher', 'arms', 'push', 'barbell', 'reps', true, false, 0, false, NULL, 880),
  ('dumbbell-skull-crusher', 'Dumbbell Skull Crusher', 'arms', 'push', 'dumbbell', 'reps', true, false, 0, false, NULL, 890),
  ('cable-pushdown', 'Cable Pushdown', 'arms', 'push', 'cable', 'reps', true, false, 0, false, '{"pushdown","tricep pushdown"}'::text[], 900),
  ('rope-pushdown', 'Rope Pushdown', 'arms', 'push', 'cable', 'reps', true, false, 0, false, NULL, 910),
  ('reverse-grip-pushdown', 'Reverse-Grip Pushdown', 'arms', 'push', 'cable', 'reps', true, false, 0, false, NULL, 920),
  ('overhead-cable-extension', 'Overhead Cable Extension', 'arms', 'push', 'cable', 'reps', true, false, 0, false, NULL, 930),
  ('overhead-rope-extension', 'Overhead Rope Extension', 'arms', 'push', 'cable', 'reps', true, false, 0, false, NULL, 940),
  ('dumbbell-overhead-extension', 'Dumbbell Overhead Extension', 'arms', 'push', 'dumbbell', 'reps', true, false, 0, false, NULL, 950),
  ('single-arm-cable-extension', 'Single-Arm Cable Extension', 'arms', 'push', 'cable', 'reps', true, true, 0, false, NULL, 960),
  ('machine-triceps-extension', 'Machine Triceps Extension', 'arms', 'push', 'machine', 'reps', true, false, 0, false, NULL, 970),
  ('dip-triceps-emphasis', 'Dip — Triceps Emphasis', 'arms', 'push', 'bodyweight', 'reps', true, false, 1, false, '{"dip"}'::text[], 980),
  ('back-squat', 'Back Squat', 'legs', 'squat', 'barbell', 'reps', true, false, 0, true, '{"squat","bb squat"}'::text[], 990),
  ('front-squat', 'Front Squat', 'legs', 'squat', 'barbell', 'reps', true, false, 0, true, NULL, 1000),
  ('high-bar-squat', 'High-Bar Squat', 'legs', 'squat', 'barbell', 'reps', true, false, 0, true, NULL, 1010),
  ('low-bar-squat', 'Low-Bar Squat', 'legs', 'squat', 'barbell', 'reps', true, false, 0, true, NULL, 1020),
  ('goblet-squat', 'Goblet Squat', 'legs', 'squat', 'dumbbell', 'reps', true, false, 0, false, NULL, 1030),
  ('smith-machine-squat', 'Smith Machine Squat', 'legs', 'squat', 'machine', 'reps', true, false, 0, false, NULL, 1040),
  ('hack-squat', 'Hack Squat', 'legs', 'squat', 'machine', 'reps', true, false, 0, false, NULL, 1050),
  ('pendulum-squat', 'Pendulum Squat', 'legs', 'squat', 'machine', 'reps', true, false, 0, false, NULL, 1060),
  ('belt-squat', 'Belt Squat', 'legs', 'squat', 'machine', 'reps', true, false, 0, false, NULL, 1070),
  ('leg-press', 'Leg Press', 'legs', 'squat', 'machine', 'reps', true, false, 0, false, '{"press"}'::text[], 1080),
  ('horizontal-leg-press', 'Horizontal Leg Press', 'legs', 'squat', 'machine', 'reps', true, false, 0, false, NULL, 1090),
  ('single-leg-press', 'Single-Leg Press', 'legs', 'squat', 'machine', 'reps', true, true, 0, false, NULL, 1100),
  ('leg-extension', 'Leg Extension', 'legs', 'squat', 'machine', 'reps', true, false, 0, false, '{"quad extension"}'::text[], 1110),
  ('single-leg-extension', 'Single-Leg Extension', 'legs', 'squat', 'machine', 'reps', true, true, 0, false, NULL, 1120),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', 'legs', 'squat', 'dumbbell', 'reps', true, true, 0, false, '{"bss","split squat"}'::text[], 1130),
  ('walking-lunge', 'Walking Lunge', 'legs', 'squat', 'dumbbell', 'reps', true, true, 0, false, NULL, 1140),
  ('reverse-lunge', 'Reverse Lunge', 'legs', 'squat', 'dumbbell', 'reps', true, true, 0, false, NULL, 1150),
  ('forward-lunge', 'Forward Lunge', 'legs', 'squat', 'dumbbell', 'reps', true, true, 0, false, NULL, 1160),
  ('step-up', 'Step-Up', 'legs', 'squat', 'dumbbell', 'reps', true, true, 0, false, NULL, 1170),
  ('romanian-deadlift', 'Romanian Deadlift', 'legs', 'hinge', 'barbell', 'reps', true, false, 0, true, '{"rdl"}'::text[], 1180),
  ('dumbbell-romanian-deadlift', 'Dumbbell Romanian Deadlift', 'legs', 'hinge', 'dumbbell', 'reps', true, false, 0, false, NULL, 1190),
  ('single-leg-romanian-deadlift', 'Single-Leg Romanian Deadlift', 'legs', 'hinge', 'dumbbell', 'reps', true, true, 0, false, '{"single leg rdl","sl rdl","single-leg rdl","one leg rdl","b stance rdl"}'::text[], 1200),
  ('stiff-leg-deadlift', 'Stiff-Leg Deadlift', 'legs', 'hinge', 'barbell', 'reps', true, false, 0, false, NULL, 1210),
  ('good-morning', 'Good Morning', 'legs', 'hinge', 'barbell', 'reps', true, false, 0, false, NULL, 1220),
  ('seated-leg-curl', 'Seated Leg Curl', 'legs', 'hinge', 'machine', 'reps', true, false, 0, false, NULL, 1230),
  ('lying-leg-curl', 'Lying Leg Curl', 'legs', 'hinge', 'machine', 'reps', true, false, 0, false, NULL, 1240),
  ('standing-leg-curl', 'Standing Leg Curl', 'legs', 'hinge', 'machine', 'reps', true, true, 0, false, NULL, 1250),
  ('nordic-hamstring-curl', 'Nordic Hamstring Curl', 'legs', 'hinge', 'bodyweight', 'reps', false, false, 0.6, false, NULL, 1260),
  ('barbell-hip-thrust', 'Barbell Hip Thrust', 'glutes', 'hinge', 'barbell', 'reps', true, false, 0, true, '{"hip thrust"}'::text[], 1270),
  ('machine-hip-thrust', 'Machine Hip Thrust', 'glutes', 'hinge', 'machine', 'reps', true, false, 0, false, NULL, 1280),
  ('glute-bridge', 'Glute Bridge', 'glutes', 'hinge', 'bodyweight', 'reps', false, false, 0, false, NULL, 1290),
  ('cable-kickback', 'Cable Kickback', 'glutes', 'hinge', 'cable', 'reps', true, true, 0, false, NULL, 1300),
  ('machine-glute-kickback', 'Machine Glute Kickback', 'glutes', 'hinge', 'machine', 'reps', true, true, 0, false, NULL, 1310),
  ('hip-abduction-machine', 'Hip Abduction Machine', 'glutes', 'hinge', 'machine', 'reps', true, false, 0, false, '{"abduction"}'::text[], 1320),
  ('hip-adduction-machine', 'Hip Adduction Machine', 'glutes', 'hinge', 'machine', 'reps', true, false, 0, false, '{"adduction"}'::text[], 1330),
  ('standing-calf-raise', 'Standing Calf Raise', 'calves', 'push', 'machine', 'reps', true, false, 0, false, '{"calf raise"}'::text[], 1340),
  ('seated-calf-raise', 'Seated Calf Raise', 'calves', 'push', 'machine', 'reps', true, false, 0, false, NULL, 1350),
  ('leg-press-calf-raise', 'Leg Press Calf Raise', 'calves', 'push', 'machine', 'reps', true, false, 0, false, NULL, 1360),
  ('hack-squat-calf-raise', 'Hack Squat Calf Raise', 'calves', 'push', 'machine', 'reps', true, false, 0, false, NULL, 1370),
  ('smith-machine-calf-raise', 'Smith Machine Calf Raise', 'calves', 'push', 'machine', 'reps', true, false, 0, false, NULL, 1380),
  ('single-leg-calf-raise', 'Single-Leg Calf Raise', 'calves', 'push', 'bodyweight', 'reps', true, true, 1, false, NULL, 1390),
  ('donkey-calf-raise', 'Donkey Calf Raise', 'calves', 'push', 'machine', 'reps', true, false, 0, false, NULL, 1400),
  ('tibialis-raise', 'Tibialis Raise', 'calves', 'push', 'bodyweight', 'reps', false, false, 0, false, NULL, 1410),
  ('tibialis-machine', 'Tibialis Machine', 'calves', 'push', 'machine', 'reps', true, false, 0, false, NULL, 1420),
  ('crunch', 'Crunch', 'core', 'core', 'bodyweight', 'reps', false, false, 0, false, NULL, 1430),
  ('cable-crunch', 'Cable Crunch', 'core', 'core', 'cable', 'reps', true, false, 0, false, NULL, 1440),
  ('machine-crunch', 'Machine Crunch', 'core', 'core', 'machine', 'reps', true, false, 0, false, NULL, 1450),
  ('reverse-crunch', 'Reverse Crunch', 'core', 'core', 'bodyweight', 'reps', false, false, 0, false, NULL, 1460),
  ('decline-sit-up', 'Decline Sit-Up', 'core', 'core', 'bodyweight', 'reps', false, false, 0, false, NULL, 1470),
  ('hanging-knee-raise', 'Hanging Knee Raise', 'core', 'core', 'bodyweight', 'reps', false, false, 0, false, NULL, 1480),
  ('hanging-leg-raise', 'Hanging Leg Raise', 'core', 'core', 'bodyweight', 'reps', false, false, 0, false, NULL, 1490),
  ('captain-s-chair-leg-raise', 'Captain''s Chair Leg Raise', 'core', 'core', 'machine', 'reps', false, false, 0, false, NULL, 1500),
  ('ab-wheel-rollout', 'Ab Wheel Rollout', 'core', 'core', 'other', 'reps', false, false, 0, false, NULL, 1510),
  ('plank', 'Plank', 'core', 'core', 'bodyweight', 'duration', false, false, 0, false, NULL, 1520),
  ('side-plank', 'Side Plank', 'core', 'core', 'bodyweight', 'duration', false, true, 0, false, NULL, 1530),
  ('dead-bug', 'Dead Bug', 'core', 'core', 'bodyweight', 'reps', false, false, 0, false, NULL, 1540),
  ('bird-dog', 'Bird Dog', 'core', 'core', 'bodyweight', 'reps', false, true, 0, false, NULL, 1550),
  ('hollow-body-hold', 'Hollow Body Hold', 'core', 'core', 'bodyweight', 'duration', false, false, 0, false, NULL, 1560),
  ('pallof-press', 'Pallof Press', 'core', 'core', 'cable', 'reps', true, true, 0, false, NULL, 1570),
  ('cable-wood-chop', 'Cable Wood Chop', 'core', 'core', 'cable', 'reps', true, true, 0, false, NULL, 1580),
  ('cable-lift', 'Cable Lift', 'core', 'core', 'cable', 'reps', true, true, 0, false, NULL, 1590),
  ('russian-twist', 'Russian Twist', 'core', 'core', 'other', 'reps', false, false, 0, false, NULL, 1600),
  ('farmer-s-carry', 'Farmer''s Carry', 'carry', 'carry', 'dumbbell', 'distance', true, false, 0, false, '{"farmers walk"}'::text[], 1610),
  ('suitcase-carry', 'Suitcase Carry', 'carry', 'carry', 'dumbbell', 'distance', true, true, 0, false, NULL, 1620),
  ('front-rack-carry', 'Front Rack Carry', 'carry', 'carry', 'barbell', 'distance', true, false, 0, false, NULL, 1630),
  ('overhead-carry', 'Overhead Carry', 'carry', 'carry', 'dumbbell', 'distance', true, false, 0, false, NULL, 1640),
  ('zercher-carry', 'Zercher Carry', 'carry', 'carry', 'barbell', 'distance', true, false, 0, false, NULL, 1650),
  ('sled-push', 'Sled Push', 'carry', 'carry', 'sled', 'distance', true, false, 0, false, NULL, 1660),
  ('sled-drag', 'Sled Drag', 'carry', 'carry', 'sled', 'distance', true, false, 0, false, NULL, 1670),
  ('backward-sled-drag', 'Backward Sled Drag', 'carry', 'carry', 'sled', 'distance', true, false, 0, false, NULL, 1680),
  ('bear-crawl', 'Bear Crawl', 'carry', 'carry', 'bodyweight', 'distance', false, false, 0, false, NULL, 1690),
  ('crab-walk', 'Crab Walk', 'carry', 'carry', 'bodyweight', 'distance', false, false, 0, false, NULL, 1700),
  ('kettlebell-swing', 'Kettlebell Swing', 'kettlebell', 'hinge', 'kettlebell', 'reps', true, false, 0, false, '{"kb swing","swing"}'::text[], 1710),
  ('single-arm-kettlebell-swing', 'Single-Arm Kettlebell Swing', 'kettlebell', 'hinge', 'kettlebell', 'reps', true, true, 0, false, NULL, 1720),
  ('kettlebell-clean', 'Kettlebell Clean', 'kettlebell', 'hinge', 'kettlebell', 'reps', true, true, 0, false, NULL, 1730),
  ('kettlebell-press', 'Kettlebell Press', 'kettlebell', 'push', 'kettlebell', 'reps', true, true, 0, false, NULL, 1740),
  ('kettlebell-clean-press', 'Kettlebell Clean & Press', 'kettlebell', 'hinge', 'kettlebell', 'reps', true, true, 0, false, NULL, 1750),
  ('kettlebell-snatch', 'Kettlebell Snatch', 'kettlebell', 'hinge', 'kettlebell', 'reps', true, true, 0, false, NULL, 1760),
  ('turkish-get-up', 'Turkish Get-Up', 'kettlebell', 'hinge', 'kettlebell', 'reps', true, true, 0, false, NULL, 1770),
  ('kettlebell-goblet-squat', 'Kettlebell Goblet Squat', 'kettlebell', 'squat', 'kettlebell', 'reps', true, false, 0, false, NULL, 1780),
  ('kettlebell-deadlift', 'Kettlebell Deadlift', 'kettlebell', 'hinge', 'kettlebell', 'reps', true, false, 0, false, NULL, 1790),
  ('kettlebell-windmill', 'Kettlebell Windmill', 'kettlebell', 'hinge', 'kettlebell', 'reps', true, true, 0, false, NULL, 1800),
  ('box-jump', 'Box Jump', 'explosive', 'elastic', 'bodyweight', 'reps', false, false, 0, false, NULL, 1810),
  ('broad-jump', 'Broad Jump', 'explosive', 'elastic', 'bodyweight', 'reps', false, false, 0, false, NULL, 1820),
  ('squat-jump', 'Squat Jump', 'explosive', 'elastic', 'bodyweight', 'reps', false, false, 0, false, NULL, 1830),
  ('jump-lunge', 'Jump Lunge', 'explosive', 'elastic', 'bodyweight', 'reps', false, true, 0, false, NULL, 1840),
  ('medicine-ball-slam', 'Medicine Ball Slam', 'explosive', 'elastic', 'other', 'reps', false, false, 0, false, NULL, 1850),
  ('rotational-medicine-ball-throw', 'Rotational Medicine Ball Throw', 'explosive', 'elastic', 'other', 'reps', false, true, 0, false, NULL, 1860),
  ('battle-ropes', 'Battle Ropes', 'cardio', 'conditioning', 'other', 'duration', false, false, 0, false, NULL, 1870),
  ('skierg', 'SkiErg', 'cardio', 'conditioning', 'machine', 'duration', false, false, 0, false, NULL, 1880),
  ('rowing-ergometer', 'Rowing Ergometer', 'cardio', 'conditioning', 'machine', 'duration', false, false, 0, false, '{"rower","erg"}'::text[], 1890),
  ('assault-bike', 'Assault Bike', 'cardio', 'conditioning', 'machine', 'duration', false, false, 0, false, '{"air bike","echo bike"}'::text[], 1900),
  ('treadmill-run', 'Treadmill Run', 'cardio', 'conditioning', 'machine', 'distance', false, false, 0, false, NULL, 1910),
  ('outdoor-run', 'Outdoor Run', 'cardio', 'conditioning', 'bodyweight', 'distance', false, false, 0, false, '{"run"}'::text[], 1920),
  ('incline-walk', 'Incline Walk', 'cardio', 'conditioning', 'machine', 'duration', false, false, 0, false, '{"ruck","walk"}'::text[], 1930),
  ('stair-climber', 'Stair Climber', 'cardio', 'conditioning', 'machine', 'duration', false, false, 0, false, NULL, 1940),
  ('jump-rope', 'Jump Rope', 'cardio', 'conditioning', 'other', 'duration', false, false, 0, false, '{"skipping"}'::text[], 1950),
  ('couch-stretch', 'Couch Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 1960),
  ('half-kneeling-hip-flexor-stretch', 'Half-Kneeling Hip Flexor Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 1970),
  ('90-90-hip-switch', '90/90 Hip Switch', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 1980),
  ('90-90-hip-stretch', '90/90 Hip Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 1990),
  ('pigeon-stretch', 'Pigeon Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2000),
  ('figure-four-stretch', 'Figure-Four Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2010),
  ('frog-stretch', 'Frog Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 2020),
  ('butterfly-stretch', 'Butterfly Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 2030),
  ('adductor-rockback', 'Adductor Rockback', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 2040),
  ('cossack-squat', 'Cossack Squat', 'mobility', 'mobility', 'bodyweight', 'reps', false, true, 0, false, NULL, 2050),
  ('deep-squat-hold', 'Deep Squat Hold', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 2060),
  ('world-s-greatest-stretch', 'World''s Greatest Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2070),
  ('standing-hamstring-stretch', 'Standing Hamstring Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2080),
  ('pancake-stretch', 'Pancake Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 2090),
  ('quad-stretch', 'Quad Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2100),
  ('calf-wall-stretch', 'Calf Wall Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2110),
  ('ankle-dorsiflexion-mobilisation', 'Ankle Dorsiflexion Mobilisation', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2120),
  ('knee-to-wall-ankle-mobilisation', 'Knee-to-Wall Ankle Mobilisation', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2130),
  ('cat-cow', 'Cat-Cow', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 2140),
  ('child-s-pose', 'Child''s Pose', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 2150),
  ('cobra', 'Cobra', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 2160),
  ('thoracic-extension', 'Thoracic Extension', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 2170),
  ('thoracic-rotation', 'Thoracic Rotation', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2180),
  ('open-book', 'Open Book', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2190),
  ('thread-the-needle', 'Thread the Needle', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2200),
  ('supine-spinal-twist', 'Supine Spinal Twist', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2210),
  ('jefferson-curl', 'Jefferson Curl', 'mobility', 'mobility', 'bodyweight', 'reps', true, false, 0, false, NULL, 2220),
  ('segmented-spinal-roll', 'Segmented Spinal Roll', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 2230),
  ('doorway-pec-stretch', 'Doorway Pec Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2240),
  ('lat-stretch', 'Lat Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2250),
  ('bench-lat-stretch', 'Bench Lat Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 2260),
  ('overhead-triceps-stretch', 'Overhead Triceps Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2270),
  ('cross-body-shoulder-stretch', 'Cross-Body Shoulder Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2280),
  ('sleeper-stretch', 'Sleeper Stretch', 'mobility', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 2290),
  ('shoulder-cars', 'Shoulder CARs', 'mobility', 'mobility', 'bodyweight', 'reps', false, true, 0, false, NULL, 2300),
  ('scapular-cars', 'Scapular CARs', 'mobility', 'mobility', 'bodyweight', 'reps', false, false, 0, false, NULL, 2310),
  ('wall-slides', 'Wall Slides', 'mobility', 'mobility', 'bodyweight', 'reps', false, false, 0, false, NULL, 2320),
  ('scapular-push-ups', 'Scapular Push-Ups', 'mobility', 'mobility', 'bodyweight', 'reps', false, false, 0, false, NULL, 2330),
  ('dead-hang', 'Dead Hang', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 2340),
  ('active-hang', 'Active Hang', 'mobility', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 2350),
  ('rebounding', 'Rebounding', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2360),
  ('pogo-hops', 'Pogo Hops', 'fascia', 'elastic', 'bodyweight', 'reps', false, false, 0, false, NULL, 2370),
  ('low-pogo-hops', 'Low Pogo Hops', 'fascia', 'elastic', 'bodyweight', 'reps', false, false, 0, false, NULL, 2380),
  ('single-leg-pogo', 'Single-Leg Pogo', 'fascia', 'elastic', 'bodyweight', 'reps', false, true, 0, false, NULL, 2390),
  ('lateral-pogo', 'Lateral Pogo', 'fascia', 'elastic', 'bodyweight', 'reps', false, true, 0, false, NULL, 2400),
  ('rhythm-bounces', 'Rhythm Bounces', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2410),
  ('heel-bounces', 'Heel Bounces', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2420),
  ('whole-body-shaking', 'Whole-Body Shaking', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, '{"shake","shaking"}'::text[], 2430),
  ('loose-limb-shaking', 'Loose Limb Shaking', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2440),
  ('elastic-arm-swings', 'Elastic Arm Swings', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2450),
  ('cross-body-arm-swings', 'Cross-Body Arm Swings', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2460),
  ('pendulum-arm-swings', 'Pendulum Arm Swings', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2470),
  ('rotational-bounces', 'Rotational Bounces', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2480),
  ('standing-spiral-rotation', 'Standing Spiral Rotation', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2490),
  ('walking-spiral', 'Walking Spiral', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2500),
  ('contralateral-walking', 'Contralateral Walking', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2510),
  ('crawling', 'Crawling', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2520),
  ('lateral-crawl', 'Lateral Crawl', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2530),
  ('loaded-pancake', 'Loaded Pancake', 'fascia', 'elastic', 'bodyweight', 'duration', true, false, 0, false, NULL, 2540),
  ('cossack-flow', 'Cossack Flow', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2550),
  ('deep-squat-flow', 'Deep Squat Flow', 'fascia', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 2560),
  ('lunge-rotation', 'Lunge + Rotation', 'fascia', 'elastic', 'bodyweight', 'duration', false, true, 0, false, NULL, 2570),
  ('side-bend-reach', 'Side Bend Reach', 'fascia', 'elastic', 'bodyweight', 'duration', false, true, 0, false, NULL, 2580),
  ('standing-lateral-line-stretch', 'Standing Lateral Line Stretch', 'fascia', 'elastic', 'bodyweight', 'duration', false, true, 0, false, NULL, 2590),
  ('cross-body-chain-stretch', 'Cross-Body Chain Stretch', 'fascia', 'elastic', 'bodyweight', 'duration', false, true, 0, false, NULL, 2600),
  ('spiral-line-stretch', 'Spiral Line Stretch', 'fascia', 'elastic', 'bodyweight', 'duration', false, true, 0, false, NULL, 2610),
  ('hanging-lateral-stretch', 'Hanging Lateral Stretch', 'fascia', 'elastic', 'bodyweight', 'duration', false, true, 0, false, NULL, 2620),
  ('hanging-rotation', 'Hanging Rotation', 'fascia', 'elastic', 'bodyweight', 'duration', false, true, 0, false, NULL, 2630),
  ('foam-roll-calves', 'Foam Roll — Calves', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2640),
  ('foam-roll-quads', 'Foam Roll — Quads', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2650),
  ('foam-roll-hamstrings', 'Foam Roll — Hamstrings', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2660),
  ('foam-roll-glutes', 'Foam Roll — Glutes', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2670),
  ('foam-roll-adductors', 'Foam Roll — Adductors', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2680),
  ('foam-roll-it-band-region', 'Foam Roll — IT-Band Region', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2690),
  ('foam-roll-thoracic-spine', 'Foam Roll — Thoracic Spine', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2700),
  ('foam-roll-lats', 'Foam Roll — Lats', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2710),
  ('lacrosse-ball-feet', 'Lacrosse Ball — Feet', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2720),
  ('lacrosse-ball-glutes', 'Lacrosse Ball — Glutes', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2730),
  ('lacrosse-ball-pec', 'Lacrosse Ball — Pec', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2740),
  ('lacrosse-ball-upper-back', 'Lacrosse Ball — Upper Back', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2750),
  ('massage-ball-hip', 'Massage Ball — Hip', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2760),
  ('peanut-ball-spine', 'Peanut Ball — Spine', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2770),
  ('foot-rolling', 'Foot Rolling', 'tissue', 'tissue', 'other', 'duration', false, false, 0, false, NULL, 2780),
  ('crocodile-breathing', 'Crocodile Breathing', 'breath', 'breath', 'bodyweight', 'duration', false, false, 0, false, NULL, 2790),
  ('90-90-breathing', '90/90 Breathing', 'breath', 'breath', 'bodyweight', 'duration', false, false, 0, false, NULL, 2800),
  ('supine-diaphragmatic-breathing', 'Supine Diaphragmatic Breathing', 'breath', 'breath', 'bodyweight', 'duration', false, false, 0, false, NULL, 2810),
  ('child-s-pose-breathing', 'Child''s Pose Breathing', 'breath', 'breath', 'bodyweight', 'duration', false, false, 0, false, NULL, 2820),
  ('deep-squat-breathing', 'Deep Squat Breathing', 'breath', 'breath', 'bodyweight', 'duration', false, false, 0, false, NULL, 2830),
  ('dead-hang-breathing', 'Dead Hang Breathing', 'breath', 'breath', 'bodyweight', 'duration', false, false, 0, false, NULL, 2840),
  ('rib-expansion-breathing', 'Rib Expansion Breathing', 'breath', 'breath', 'bodyweight', 'duration', false, false, 0, false, NULL, 2850),
  ('lateral-rib-breathing', 'Lateral Rib Breathing', 'breath', 'breath', 'bodyweight', 'duration', false, false, 0, false, NULL, 2860),
  ('cat-cow-breath', 'Cat-Cow + Breath', 'breath', 'breath', 'bodyweight', 'duration', false, false, 0, false, NULL, 2870),
  ('segmental-breathing', 'Segmental Breathing', 'breath', 'breath', 'bodyweight', 'duration', false, false, 0, false, NULL, 2880),
  ('box-breathing', 'Box Breathing', 'breath', 'breath', 'bodyweight', 'duration', false, false, 0, false, NULL, 2890),
  ('extended-exhale-breathing', 'Extended-Exhale Breathing', 'breath', 'breath', 'bodyweight', 'duration', false, false, 0, false, NULL, 2900),
  ('walking-breath-practice', 'Walking Breath Practice', 'breath', 'breath', 'bodyweight', 'duration', false, false, 0, false, NULL, 2910),
  ('power-clean', 'Power Clean', 'olympic', 'hinge', 'barbell', 'reps', true, false, 0, true, '{"clean"}'::text[], 2920),
  ('hang-clean', 'Hang Clean', 'olympic', 'hinge', 'barbell', 'reps', true, false, 0, false, NULL, 2930),
  ('clean-jerk', 'Clean & Jerk', 'olympic', 'hinge', 'barbell', 'reps', true, false, 0, false, NULL, 2940),
  ('power-snatch', 'Power Snatch', 'olympic', 'hinge', 'barbell', 'reps', true, false, 0, false, '{"snatch"}'::text[], 2950),
  ('hang-snatch', 'Hang Snatch', 'olympic', 'hinge', 'barbell', 'reps', true, false, 0, false, NULL, 2960),
  ('push-press', 'Push Press', 'olympic', 'push', 'barbell', 'reps', true, false, 0, false, NULL, 2970),
  ('push-jerk', 'Push Jerk', 'olympic', 'push', 'barbell', 'reps', true, false, 0, false, NULL, 2980),
  ('high-pull', 'High Pull', 'olympic', 'hinge', 'barbell', 'reps', true, false, 0, false, NULL, 2990),
  ('clean-pull', 'Clean Pull', 'olympic', 'hinge', 'barbell', 'reps', true, false, 0, false, NULL, 3000),
  ('snatch-pull', 'Snatch Pull', 'olympic', 'hinge', 'barbell', 'reps', true, false, 0, false, NULL, 3010),
  ('landmine-press', 'Landmine Press', 'landmine', 'push', 'barbell', 'reps', true, true, 0, false, NULL, 3020),
  ('single-arm-landmine-press', 'Single-Arm Landmine Press', 'landmine', 'push', 'barbell', 'reps', true, true, 0, false, NULL, 3030),
  ('landmine-row', 'Landmine Row', 'landmine', 'pull', 'barbell', 'reps', true, false, 0, false, NULL, 3040),
  ('landmine-squat', 'Landmine Squat', 'landmine', 'squat', 'barbell', 'reps', true, false, 0, false, NULL, 3050),
  ('landmine-rdl', 'Landmine RDL', 'landmine', 'hinge', 'barbell', 'reps', true, false, 0, false, NULL, 3060),
  ('landmine-rotation', 'Landmine Rotation', 'landmine', 'rotation', 'barbell', 'reps', true, true, 0, false, NULL, 3070),
  ('landmine-lunge', 'Landmine Lunge', 'landmine', 'squat', 'barbell', 'reps', true, true, 0, false, NULL, 3080),
  ('inverted-row', 'Inverted Row', 'calisthenics', 'pull', 'bodyweight', 'reps', false, false, 0, false, '{"australian pull-up"}'::text[], 3090),
  ('pike-push-up', 'Pike Push-Up', 'calisthenics', 'push', 'bodyweight', 'reps', false, false, 0, false, NULL, 3100),
  ('handstand-push-up', 'Handstand Push-Up', 'calisthenics', 'push', 'bodyweight', 'reps', false, false, 0, false, '{"hspu"}'::text[], 3110),
  ('handstand-hold', 'Handstand Hold', 'calisthenics', 'isometric', 'bodyweight', 'duration', false, false, 0, false, NULL, 3120),
  ('l-sit', 'L-Sit', 'calisthenics', 'isometric', 'bodyweight', 'duration', false, false, 0, false, NULL, 3130),
  ('muscle-up', 'Muscle-Up', 'calisthenics', 'pull', 'bodyweight', 'reps', false, false, 0, false, NULL, 3140),
  ('scapular-pull-up', 'Scapular Pull-Up', 'calisthenics', 'pull', 'bodyweight', 'reps', false, false, 0, false, NULL, 3150),
  ('reverse-nordic', 'Reverse Nordic', 'calisthenics', 'squat', 'bodyweight', 'reps', false, false, 0, false, NULL, 3160),
  ('sissy-squat', 'Sissy Squat', 'calisthenics', 'squat', 'bodyweight', 'reps', false, false, 0, false, NULL, 3170),
  ('shrimp-squat', 'Shrimp Squat', 'calisthenics', 'squat', 'bodyweight', 'reps', false, true, 0, false, NULL, 3180),
  ('pistol-squat', 'Pistol Squat', 'calisthenics', 'squat', 'bodyweight', 'reps', false, true, 0, false, NULL, 3190),
  ('ring-support-hold', 'Ring Support Hold', 'rings', 'isometric', 'rings', 'duration', false, false, 0, false, NULL, 3200),
  ('ring-push-up', 'Ring Push-Up', 'rings', 'push', 'rings', 'reps', false, false, 0, false, NULL, 3210),
  ('ring-fly', 'Ring Fly', 'rings', 'push', 'rings', 'reps', false, false, 0, false, NULL, 3220),
  ('ring-fallout', 'Ring Fallout', 'rings', 'core', 'rings', 'reps', false, false, 0, false, NULL, 3230),
  ('ring-row', 'Ring Row', 'rings', 'pull', 'rings', 'reps', false, false, 0, false, NULL, 3240),
  ('ring-dip', 'Ring Dip', 'rings', 'push', 'rings', 'reps', false, false, 0, false, NULL, 3250),
  ('skin-the-cat', 'Skin the Cat', 'rings', 'pull', 'rings', 'reps', false, false, 0, false, NULL, 3260),
  ('german-hang', 'German Hang', 'rings', 'pull', 'rings', 'duration', false, false, 0, false, NULL, 3270),
  ('front-lever-progression', 'Front-Lever Progression', 'rings', 'pull', 'rings', 'duration', false, false, 0, false, NULL, 3280),
  ('back-lever-progression', 'Back-Lever Progression', 'rings', 'pull', 'rings', 'duration', false, false, 0, false, NULL, 3290),
  ('barbell-shrug', 'Barbell Shrug', 'neck_grip', 'pull', 'barbell', 'reps', true, false, 0, false, '{"shrug"}'::text[], 3300),
  ('dumbbell-shrug', 'Dumbbell Shrug', 'neck_grip', 'pull', 'dumbbell', 'reps', true, false, 0, false, NULL, 3310),
  ('machine-shrug', 'Machine Shrug', 'neck_grip', 'pull', 'machine', 'reps', true, false, 0, false, NULL, 3320),
  ('cable-shrug', 'Cable Shrug', 'neck_grip', 'pull', 'cable', 'reps', true, false, 0, false, NULL, 3330),
  ('neck-flexion', 'Neck Flexion', 'neck_grip', 'carry', 'other', 'reps', true, false, 0, false, NULL, 3340),
  ('neck-extension', 'Neck Extension', 'neck_grip', 'carry', 'other', 'reps', true, false, 0, false, NULL, 3350),
  ('neck-lateral-flexion', 'Neck Lateral Flexion', 'neck_grip', 'carry', 'other', 'reps', true, true, 0, false, NULL, 3360),
  ('plate-pinch', 'Plate Pinch', 'neck_grip', 'carry', 'other', 'duration', true, false, 0, false, NULL, 3370),
  ('towel-hang', 'Towel Hang', 'neck_grip', 'carry', 'other', 'duration', false, false, 0, false, NULL, 3380),
  ('farmer-hold', 'Farmer Hold', 'neck_grip', 'carry', 'other', 'duration', true, false, 0, false, NULL, 3390),
  ('gripper-work', 'Gripper Work', 'neck_grip', 'carry', 'other', 'reps', true, false, 0, false, NULL, 3400),
  ('short-foot-exercise', 'Short-Foot Exercise', 'feet', 'balance', 'bodyweight', 'duration', false, false, 0, false, NULL, 3410),
  ('toe-yoga', 'Toe Yoga', 'feet', 'balance', 'bodyweight', 'duration', false, false, 0, false, NULL, 3420),
  ('toe-spreading', 'Toe Spreading', 'feet', 'balance', 'bodyweight', 'duration', false, false, 0, false, NULL, 3430),
  ('big-toe-extension', 'Big-Toe Extension', 'feet', 'balance', 'bodyweight', 'duration', false, false, 0, false, NULL, 3440),
  ('foot-doming', 'Foot Doming', 'feet', 'balance', 'bodyweight', 'duration', false, false, 0, false, NULL, 3450),
  ('barefoot-balance', 'Barefoot Balance', 'feet', 'balance', 'bodyweight', 'duration', false, true, 0, false, NULL, 3460),
  ('soleus-raise', 'Soleus Raise', 'feet', 'balance', 'bodyweight', 'reps', false, false, 0, false, NULL, 3470),
  ('calf-isometric', 'Calf Isometric', 'feet', 'isometric', 'bodyweight', 'duration', false, false, 0, false, NULL, 3480),
  ('cable-rotation', 'Cable Rotation', 'rotation', 'rotation', 'cable', 'reps', true, true, 0, false, NULL, 3490),
  ('cable-chop', 'Cable Chop', 'rotation', 'rotation', 'cable', 'reps', true, true, 0, false, NULL, 3500),
  ('cable-lift-rotation', 'Cable Lift Rotation', 'rotation', 'rotation', 'cable', 'reps', true, true, 0, false, NULL, 3510),
  ('rotational-lunge', 'Rotational Lunge', 'rotation', 'rotation', 'bodyweight', 'reps', false, true, 0, false, NULL, 3520),
  ('split-stance-rotation', 'Split-Stance Rotation', 'rotation', 'rotation', 'bodyweight', 'reps', false, true, 0, false, NULL, 3530),
  ('cable-external-rotation', 'Cable External Rotation', 'rotation', 'rotation', 'cable', 'reps', true, true, 0, false, NULL, 3540),
  ('cable-internal-rotation', 'Cable Internal Rotation', 'rotation', 'rotation', 'cable', 'reps', true, true, 0, false, NULL, 3550),
  ('cable-y-raise', 'Cable Y-Raise', 'rotation', 'rotation', 'cable', 'reps', true, false, 0, false, NULL, 3560),
  ('cable-pull-through', 'Cable Pull-Through', 'rotation', 'hinge', 'cable', 'reps', true, false, 0, false, NULL, 3570),
  ('cable-upright-row', 'Cable Upright Row', 'rotation', 'pull', 'cable', 'reps', true, false, 0, false, NULL, 3580),
  ('wall-sit', 'Wall Sit', 'isometric', 'isometric', 'bodyweight', 'duration', false, false, 0, false, NULL, 3590),
  ('split-squat-hold', 'Split-Squat Hold', 'isometric', 'isometric', 'bodyweight', 'duration', false, true, 0, false, NULL, 3600),
  ('horse-stance', 'Horse Stance', 'isometric', 'isometric', 'bodyweight', 'duration', false, false, 0, false, NULL, 3610),
  ('glute-bridge-hold', 'Glute Bridge Hold', 'isometric', 'isometric', 'bodyweight', 'duration', false, false, 0, false, NULL, 3620),
  ('copenhagen-hold', 'Copenhagen Hold', 'isometric', 'isometric', 'bodyweight', 'duration', false, true, 0, false, NULL, 3630),
  ('push-up-hold', 'Push-Up Hold', 'isometric', 'isometric', 'bodyweight', 'duration', false, false, 0, false, NULL, 3640),
  ('pull-up-hold', 'Pull-Up Hold', 'isometric', 'isometric', 'bodyweight', 'duration', false, false, 0, false, NULL, 3650),
  ('calf-hold', 'Calf Hold', 'isometric', 'isometric', 'bodyweight', 'duration', false, false, 0, false, NULL, 3660),
  ('single-leg-balance', 'Single-Leg Balance', 'balance', 'balance', 'bodyweight', 'duration', false, true, 0, false, NULL, 3670),
  ('single-leg-reach', 'Single-Leg Reach', 'balance', 'balance', 'bodyweight', 'duration', false, true, 0, false, NULL, 3680),
  ('airplane', 'Airplane', 'balance', 'balance', 'bodyweight', 'duration', false, true, 0, false, NULL, 3690),
  ('balance-board', 'Balance Board', 'balance', 'balance', 'other', 'duration', false, false, 0, false, NULL, 3700),
  ('bosu-balance', 'Bosu Balance', 'balance', 'balance', 'other', 'duration', false, false, 0, false, NULL, 3710),
  ('single-leg-rdl-reach', 'Single-Leg RDL Reach', 'balance', 'balance', 'bodyweight', 'duration', false, true, 0, false, NULL, 3720),
  ('depth-jump', 'Depth Jump', 'plyometric', 'elastic', 'bodyweight', 'reps', false, false, 0, false, NULL, 3730),
  ('drop-jump', 'Drop Jump', 'plyometric', 'elastic', 'bodyweight', 'reps', false, false, 0, false, NULL, 3740),
  ('lateral-bound', 'Lateral Bound', 'plyometric', 'elastic', 'bodyweight', 'reps', false, true, 0, false, NULL, 3750),
  ('skater-jump', 'Skater Jump', 'plyometric', 'elastic', 'bodyweight', 'reps', false, true, 0, false, NULL, 3760),
  ('single-leg-hop', 'Single-Leg Hop', 'plyometric', 'elastic', 'bodyweight', 'reps', false, true, 0, false, NULL, 3770),
  ('bounds', 'Bounds', 'plyometric', 'elastic', 'bodyweight', 'reps', false, false, 0, false, NULL, 3780),
  ('hurdle-hop', 'Hurdle Hop', 'plyometric', 'elastic', 'bodyweight', 'reps', false, false, 0, false, NULL, 3790),
  ('lateral-shuffle', 'Lateral Shuffle', 'agility', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 3800),
  ('carioca', 'Carioca', 'agility', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 3810),
  ('cone-drill', 'Cone Drill', 'agility', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 3820),
  ('ladder-drill', 'Ladder Drill', 'agility', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 3830),
  ('shuttle-run', 'Shuttle Run', 'agility', 'locomotion', 'bodyweight', 'distance', false, false, 0, false, NULL, 3840),
  ('5-10-5-drill', '5-10-5 Drill', 'agility', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 3850),
  ('t-drill', 'T-Drill', 'agility', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 3860),
  ('deceleration-drill', 'Deceleration Drill', 'agility', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 3870),
  ('backward-running', 'Backward Running', 'agility', 'locomotion', 'bodyweight', 'distance', false, false, 0, false, NULL, 3880),
  ('footwork-drill', 'Footwork Drill', 'agility', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 3890),
  ('reaction-drill', 'Reaction Drill', 'agility', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 3900),
  ('sprinting', 'Sprinting', 'locomotion', 'locomotion', 'bodyweight', 'distance', false, false, 0, false, '{"sprints"}'::text[], 3910),
  ('acceleration-sprint', 'Acceleration Sprint', 'locomotion', 'locomotion', 'bodyweight', 'distance', false, false, 0, false, NULL, 3920),
  ('flying-sprint', 'Flying Sprint', 'locomotion', 'locomotion', 'bodyweight', 'distance', false, false, 0, false, NULL, 3930),
  ('hill-sprint', 'Hill Sprint', 'locomotion', 'locomotion', 'bodyweight', 'distance', false, false, 0, false, NULL, 3940),
  ('resisted-sprint', 'Resisted Sprint', 'locomotion', 'locomotion', 'sled', 'distance', false, false, 0, false, NULL, 3950),
  ('stair-climbing', 'Stair Climbing', 'locomotion', 'locomotion', 'bodyweight', 'distance', false, false, 0, false, NULL, 3960),
  ('skipping', 'Skipping', 'locomotion', 'locomotion', 'bodyweight', 'distance', false, false, 0, false, NULL, 3970),
  ('leopard-crawl', 'Leopard Crawl', 'ground', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 3980),
  ('ape', 'Ape', 'ground', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 3990),
  ('beast-hold', 'Beast Hold', 'ground', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 4000),
  ('beast-reach', 'Beast Reach', 'ground', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 4010),
  ('frogger', 'Frogger', 'ground', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 4020),
  ('lizard-crawl', 'Lizard Crawl', 'ground', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 4030),
  ('duck-walk', 'Duck Walk', 'ground', 'locomotion', 'bodyweight', 'duration', false, false, 0, false, NULL, 4040),
  ('downward-dog', 'Downward Dog', 'yoga', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 4050),
  ('upward-dog', 'Upward Dog', 'yoga', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 4060),
  ('low-lunge', 'Low Lunge', 'yoga', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 4070),
  ('warrior-i', 'Warrior I', 'yoga', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 4080),
  ('warrior-ii', 'Warrior II', 'yoga', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 4090),
  ('triangle-pose', 'Triangle Pose', 'yoga', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 4100),
  ('garland-squat', 'Garland Squat', 'yoga', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 4110),
  ('happy-baby', 'Happy Baby', 'yoga', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 4120),
  ('puppy-pose', 'Puppy Pose', 'yoga', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 4130),
  ('sphinx-pose', 'Sphinx Pose', 'yoga', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 4140),
  ('legs-up-the-wall', 'Legs-Up-the-Wall', 'yoga', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 4150),
  ('pandiculation', 'Pandiculation', 'somatic', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 4160),
  ('pelvic-rocking', 'Pelvic Rocking', 'somatic', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 4170),
  ('spinal-waves', 'Spinal Waves', 'somatic', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 4180),
  ('undulation', 'Undulation', 'somatic', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 4190),
  ('freeform-movement', 'Freeform Movement', 'somatic', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 4200),
  ('constructive-rest', 'Constructive Rest', 'somatic', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 4210),
  ('elastic-pulsing', 'Elastic Pulsing', 'somatic', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 4220),
  ('oscillatory-squat', 'Oscillatory Squat', 'somatic', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 4230),
  ('multi-planar-bouncing', 'Multi-Planar Bouncing', 'somatic', 'elastic', 'bodyweight', 'duration', false, false, 0, false, NULL, 4240),
  ('pilates-hundred', 'Pilates Hundred', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, '{"hundred"}'::text[], 4250),
  ('roll-up', 'Roll-Up', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4260),
  ('roll-over', 'Roll-Over', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4270),
  ('rolling-like-a-ball', 'Rolling Like a Ball', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4280),
  ('single-leg-stretch', 'Single-Leg Stretch', 'pilates', 'core', 'mat', 'reps', false, true, 0, false, NULL, 4290),
  ('double-leg-stretch', 'Double-Leg Stretch', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4300),
  ('single-straight-leg-stretch', 'Single Straight-Leg Stretch', 'pilates', 'core', 'mat', 'reps', false, true, 0, false, '{"scissors"}'::text[], 4310),
  ('criss-cross', 'Criss-Cross', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, '{"bicycle"}'::text[], 4320),
  ('spine-stretch-forward', 'Spine Stretch Forward', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4330),
  ('open-leg-rocker', 'Open-Leg Rocker', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4340),
  ('corkscrew', 'Corkscrew', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4350),
  ('saw', 'Saw', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4360),
  ('swan', 'Swan', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4370),
  ('single-leg-kick', 'Single-Leg Kick', 'pilates', 'core', 'mat', 'reps', false, true, 0, false, NULL, 4380),
  ('double-leg-kick', 'Double-Leg Kick', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4390),
  ('neck-pull', 'Neck Pull', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4400),
  ('shoulder-bridge', 'Shoulder Bridge', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4410),
  ('spine-twist', 'Spine Twist', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4420),
  ('teaser', 'Teaser', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4430),
  ('pilates-swimming', 'Pilates Swimming', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4440),
  ('leg-pull-front', 'Leg Pull Front', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4450),
  ('leg-pull-back', 'Leg Pull Back', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4460),
  ('side-kick-series', 'Side-Kick Series', 'pilates', 'core', 'mat', 'reps', false, true, 0, false, NULL, 4470),
  ('pilates-leg-circles', 'Pilates Leg Circles', 'pilates', 'core', 'mat', 'reps', false, true, 0, false, NULL, 4480),
  ('mermaid', 'Mermaid', 'pilates', 'core', 'mat', 'reps', false, true, 0, false, NULL, 4490),
  ('boomerang', 'Boomerang', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4500),
  ('seal', 'Seal', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4510),
  ('pilates-push-up', 'Pilates Push-Up', 'pilates', 'core', 'mat', 'reps', false, false, 0, false, NULL, 4520),
  ('pilates-plank-series', 'Pilates Plank Series', 'pilates', 'core', 'mat', 'duration', false, false, 0, false, NULL, 4530),
  ('pilates-ring-squeeze', 'Pilates Ring Squeeze', 'pilates', 'core', 'pilates_ring', 'reps', false, false, 0, false, '{"magic circle"}'::text[], 4540),
  ('pilates-ring-arm-press', 'Pilates Ring Arm Press', 'pilates', 'core', 'pilates_ring', 'reps', false, false, 0, false, NULL, 4550),
  ('reformer-footwork', 'Reformer Footwork', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, '{"footwork"}'::text[], 4560),
  ('reformer-hundred', 'Reformer Hundred', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4570),
  ('reformer-leg-circles', 'Reformer Leg Circles', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4580),
  ('reformer-frog', 'Reformer Frog', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4590),
  ('reformer-short-spine', 'Reformer Short Spine', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4600),
  ('reformer-long-spine', 'Reformer Long Spine', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4610),
  ('reformer-coordination', 'Reformer Coordination', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4620),
  ('reformer-rowing', 'Reformer Rowing', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4630),
  ('reformer-arm-series', 'Reformer Arm Series', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4640),
  ('reformer-pulling-straps', 'Reformer Pulling Straps', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4650),
  ('reformer-long-box-backstroke', 'Reformer Long Box Backstroke', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4660),
  ('reformer-short-box-series', 'Reformer Short Box Series', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4670),
  ('reformer-stomach-massage', 'Reformer Stomach Massage', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4680),
  ('reformer-long-stretch', 'Reformer Long Stretch', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4690),
  ('reformer-down-stretch', 'Reformer Down Stretch', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4700),
  ('reformer-up-stretch', 'Reformer Up Stretch', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4710),
  ('reformer-elephant', 'Reformer Elephant', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4720),
  ('reformer-knee-stretches', 'Reformer Knee Stretches', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4730),
  ('reformer-scooter', 'Reformer Scooter', 'pilates', 'core', 'reformer', 'reps', false, true, 0, false, NULL, 4740),
  ('reformer-lunge', 'Reformer Lunge', 'pilates', 'core', 'reformer', 'reps', false, true, 0, false, '{"reformer lunges"}'::text[], 4750),
  ('reformer-side-splits', 'Reformer Side Splits', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4760),
  ('reformer-front-splits', 'Reformer Front Splits', 'pilates', 'core', 'reformer', 'reps', false, true, 0, false, NULL, 4770),
  ('reformer-mermaid', 'Reformer Mermaid', 'pilates', 'core', 'reformer', 'reps', false, true, 0, false, NULL, 4780),
  ('reformer-semi-circle', 'Reformer Semi-Circle', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4790),
  ('reformer-tendon-stretch', 'Reformer Tendon Stretch', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4800),
  ('reformer-snake-twist', 'Reformer Snake & Twist', 'pilates', 'core', 'reformer', 'reps', false, false, 0, false, NULL, 4810),
  ('cadillac-roll-down', 'Cadillac Roll-Down', 'pilates', 'core', 'cadillac', 'reps', false, false, 0, false, '{"trapeze table"}'::text[], 4820),
  ('cadillac-leg-springs', 'Cadillac Leg Springs', 'pilates', 'core', 'cadillac', 'reps', false, false, 0, false, NULL, 4830),
  ('cadillac-arm-springs', 'Cadillac Arm Springs', 'pilates', 'core', 'cadillac', 'reps', false, false, 0, false, NULL, 4840),
  ('cadillac-push-through-bar', 'Cadillac Push-Through Bar', 'pilates', 'core', 'cadillac', 'reps', false, false, 0, false, NULL, 4850),
  ('cadillac-hanging-series', 'Cadillac Hanging Series', 'pilates', 'core', 'cadillac', 'duration', false, false, 0, false, NULL, 4860),
  ('chair-pumping', 'Chair Pumping', 'pilates', 'core', 'chair', 'reps', false, false, 0, false, '{"wunda chair"}'::text[], 4870),
  ('chair-push-down', 'Chair Push-Down', 'pilates', 'core', 'chair', 'reps', false, false, 0, false, NULL, 4880),
  ('chair-step-up', 'Chair Step-Up', 'pilates', 'core', 'chair', 'reps', false, true, 0, false, NULL, 4890),
  ('chair-mountain-climber', 'Chair Mountain Climber', 'pilates', 'core', 'chair', 'reps', false, true, 0, false, NULL, 4900),
  ('chair-teaser', 'Chair Teaser', 'pilates', 'core', 'chair', 'reps', false, false, 0, false, NULL, 4910),
  ('spine-corrector-arc', 'Spine Corrector Arc', 'pilates', 'core', 'spine_corrector', 'reps', false, false, 0, false, NULL, 4920),
  ('ladder-barrel-swan', 'Ladder Barrel Swan', 'pilates', 'core', 'barrel', 'reps', false, false, 0, false, NULL, 4930),
  ('lagree-bear', 'Lagree Bear', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, '{"bear"}'::text[], 4940),
  ('lagree-wheelbarrow', 'Lagree Wheelbarrow', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 4950),
  ('lagree-pike', 'Lagree Pike', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 4960),
  ('lagree-plank', 'Lagree Plank', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 4970),
  ('lagree-saw', 'Lagree Saw', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 4980),
  ('lagree-french-twist', 'Lagree French Twist', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 4990),
  ('lagree-catfish', 'Lagree Catfish', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 5000),
  ('lagree-elevator-lunge', 'Lagree Elevator Lunge', 'lagree', 'core', 'megaformer', 'duration', false, true, 0, false, NULL, 5010),
  ('lagree-giant-reverse-lunge', 'Lagree Giant Reverse Lunge', 'lagree', 'core', 'megaformer', 'duration', false, true, 0, false, NULL, 5020),
  ('lagree-super-lunge', 'Lagree Super Lunge', 'lagree', 'core', 'megaformer', 'duration', false, true, 0, false, NULL, 5030),
  ('lagree-escalator', 'Lagree Escalator', 'lagree', 'core', 'megaformer', 'duration', false, true, 0, false, NULL, 5040),
  ('lagree-skating', 'Lagree Skating', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 5050),
  ('lagree-carriage-kick', 'Lagree Carriage Kick', 'lagree', 'core', 'megaformer', 'duration', false, true, 0, false, NULL, 5060),
  ('lagree-cobra', 'Lagree Cobra', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 5070),
  ('lagree-mermaid', 'Lagree Mermaid', 'lagree', 'core', 'megaformer', 'duration', false, true, 0, false, NULL, 5080),
  ('lagree-scrambled-eggs', 'Lagree Scrambled Eggs', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 5090),
  ('lagree-spoon', 'Lagree Spoon', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 5100),
  ('lagree-teaser', 'Lagree Teaser', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 5110),
  ('lagree-kneeling-kickback', 'Lagree Kneeling Kickback', 'lagree', 'core', 'megaformer', 'duration', false, true, 0, false, NULL, 5120),
  ('lagree-wheel-barrow-to-bear', 'Lagree Wheel Barrow to Bear', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 5130),
  ('lagree-serve-the-platter', 'Lagree Serve the Platter', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 5140),
  ('lagree-arm-series', 'Lagree Arm Series', 'lagree', 'core', 'megaformer', 'duration', false, false, 0, false, NULL, 5150),
  ('lagree-oblique-series', 'Lagree Oblique Series', 'lagree', 'core', 'megaformer', 'duration', false, true, 0, false, NULL, 5160),
  ('barre-pli-series', 'Barre Plié Series', 'barre', 'core', 'barre', 'reps', false, false, 0, false, NULL, 5170),
  ('barre-relev', 'Barre Relevé', 'barre', 'core', 'barre', 'reps', false, false, 0, false, NULL, 5180),
  ('barre-curtsy-pulse', 'Barre Curtsy Pulse', 'barre', 'core', 'barre', 'reps', false, true, 0, false, NULL, 5190),
  ('barre-attitude-lift', 'Barre Attitude Lift', 'barre', 'core', 'barre', 'reps', false, true, 0, false, NULL, 5200),
  ('barre-arabesque-lift', 'Barre Arabesque Lift', 'barre', 'core', 'barre', 'reps', false, true, 0, false, NULL, 5210),
  ('barre-grand-battement', 'Barre Grand Battement', 'barre', 'core', 'barre', 'reps', false, true, 0, false, NULL, 5220),
  ('barre-pass-balance', 'Barre Passé Balance', 'barre', 'core', 'barre', 'duration', false, true, 0, false, NULL, 5230),
  ('barre-chair-pose-pulse', 'Barre Chair Pose Pulse', 'barre', 'core', 'barre', 'duration', false, false, 0, false, NULL, 5240),
  ('barre-thigh-dancing', 'Barre Thigh Dancing', 'barre', 'core', 'barre', 'duration', false, false, 0, false, NULL, 5250),
  ('barre-seat-work', 'Barre Seat Work', 'barre', 'core', 'barre', 'reps', false, false, 0, false, NULL, 5260),
  ('barre-ab-series', 'Barre Ab Series', 'barre', 'core', 'barre', 'reps', false, false, 0, false, NULL, 5270),
  ('barre-port-de-bras', 'Barre Port de Bras', 'barre', 'core', 'barre', 'reps', false, false, 0, false, NULL, 5280),
  ('barre-fold-over', 'Barre Fold-Over', 'barre', 'core', 'barre', 'reps', false, true, 0, false, NULL, 5290),
  ('barre-clamshell', 'Barre Clamshell', 'barre', 'core', 'barre', 'reps', false, true, 0, false, NULL, 5300),
  ('chin-tuck', 'Chin Tuck', 'corrective', 'mobility', 'bodyweight', 'reps', false, false, 0, false, NULL, 5310),
  ('wall-angel', 'Wall Angel', 'corrective', 'mobility', 'bodyweight', 'reps', false, false, 0, false, NULL, 5320),
  ('serratus-wall-slide', 'Serratus Wall Slide', 'corrective', 'mobility', 'bodyweight', 'reps', false, false, 0, false, NULL, 5330),
  ('scapular-retraction', 'Scapular Retraction', 'corrective', 'mobility', 'bodyweight', 'reps', false, false, 0, false, NULL, 5340),
  ('y-t-w-raises', 'Y-T-W Raises', 'corrective', 'mobility', 'dumbbell', 'reps', true, false, 0, false, NULL, 5350),
  ('hip-airplane', 'Hip Airplane', 'corrective', 'mobility', 'bodyweight', 'reps', false, true, 0, false, NULL, 5360),
  ('pelvic-tilt', 'Pelvic Tilt', 'corrective', 'mobility', 'bodyweight', 'reps', false, false, 0, false, NULL, 5370),
  ('pelvic-clock', 'Pelvic Clock', 'corrective', 'mobility', 'bodyweight', 'reps', false, false, 0, false, NULL, 5380),
  ('bear-hold', 'Bear Hold', 'corrective', 'mobility', 'bodyweight', 'duration', false, false, 0, false, NULL, 5390),
  ('copenhagen-plank', 'Copenhagen Plank', 'corrective', 'mobility', 'bodyweight', 'duration', false, true, 0, false, NULL, 5400),
  ('easy-walk', 'Easy Walk', 'recovery', 'recovery', 'bodyweight', 'duration', false, false, 0, false, NULL, 5410),
  ('recovery-bike', 'Recovery Bike', 'recovery', 'recovery', 'machine', 'duration', false, false, 0, false, NULL, 5420),
  ('gentle-rebounding', 'Gentle Rebounding', 'recovery', 'recovery', 'bodyweight', 'duration', false, false, 0, false, NULL, 5430),
  ('passive-hang', 'Passive Hang', 'recovery', 'recovery', 'bodyweight', 'duration', false, false, 0, false, NULL, 5440),
  ('supported-deep-squat', 'Supported Deep Squat', 'recovery', 'recovery', 'bodyweight', 'duration', false, false, 0, false, NULL, 5450),
  ('massage-gun', 'Massage Gun', 'recovery', 'recovery', 'other', 'duration', false, false, 0, false, NULL, 5460),
  ('mobility-stick', 'Mobility Stick', 'recovery', 'recovery', 'other', 'duration', false, false, 0, false, NULL, 5470),
  ('yoga-flow', 'Yoga Flow', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5480),
  ('mobility-flow', 'Mobility Flow', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5490),
  ('fascial-flow', 'Fascial Flow', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5500),
  ('animal-flow', 'Animal Flow', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5510),
  ('somatic-movement', 'Somatic Movement', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5520),
  ('dynamic-warm-up', 'Dynamic Warm-Up', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5530),
  ('full-body-stretch', 'Full-Body Stretch', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5540),
  ('upper-body-mobility', 'Upper-Body Mobility', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5550),
  ('lower-body-mobility', 'Lower-Body Mobility', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5560),
  ('hip-mobility', 'Hip Mobility', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5570),
  ('shoulder-mobility', 'Shoulder Mobility', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5580),
  ('spinal-mobility', 'Spinal Mobility', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5590),
  ('recovery-session', 'Recovery Session', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5600),
  ('breathwork-session', 'Breathwork Session', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5610),
  ('rebounding-session', 'Rebounding Session', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5620),
  ('sauna', 'Sauna', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5630),
  ('cold-plunge', 'Cold Plunge', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5640),
  ('cooldown', 'Cooldown', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5650),
  ('custom-activity', 'Custom Activity', 'practice', 'flow', 'bodyweight', 'duration', false, false, 0, false, NULL, 5660),
  ('mat-pilates', 'Mat Pilates', 'class', 'flow', 'other', 'duration', false, false, 0, false, '{"pilates class"}'::text[], 5670),
  ('reformer-pilates', 'Reformer Pilates', 'class', 'flow', 'reformer', 'duration', false, false, 0, false, '{"pilates reformer"}'::text[], 5680),
  ('cadillac-session', 'Cadillac Session', 'class', 'flow', 'cadillac', 'duration', false, false, 0, false, NULL, 5690),
  ('chair-session', 'Chair Session', 'class', 'flow', 'chair', 'duration', false, false, 0, false, NULL, 5700),
  ('lagree', 'Lagree', 'class', 'flow', 'megaformer', 'duration', false, false, 0, false, '{"megaformer","lagree class"}'::text[], 5710),
  ('barre-class', 'Barre Class', 'class', 'flow', 'barre', 'duration', false, false, 0, false, '{"barre"}'::text[], 5720),
  ('yoga-class', 'Yoga Class', 'class', 'flow', 'other', 'duration', false, false, 0, false, '{"yoga"}'::text[], 5730),
  ('vinyasa', 'Vinyasa', 'class', 'flow', 'other', 'duration', false, false, 0, false, NULL, 5740),
  ('hot-yoga', 'Hot Yoga', 'class', 'flow', 'other', 'duration', false, false, 0, false, '{"bikram"}'::text[], 5750),
  ('yin-yoga', 'Yin Yoga', 'class', 'flow', 'other', 'duration', false, false, 0, false, NULL, 5760),
  ('hatha-yoga', 'Hatha Yoga', 'class', 'flow', 'other', 'duration', false, false, 0, false, NULL, 5770),
  ('power-yoga', 'Power Yoga', 'class', 'flow', 'other', 'duration', false, false, 0, false, NULL, 5780),
  ('ashtanga', 'Ashtanga', 'class', 'flow', 'other', 'duration', false, false, 0, false, NULL, 5790),
  ('restorative-yoga', 'Restorative Yoga', 'class', 'flow', 'other', 'duration', false, false, 0, false, NULL, 5800),
  ('spin-class', 'Spin Class', 'class', 'flow', 'machine', 'duration', false, false, 0, false, '{"spin","indoor cycling"}'::text[], 5810),
  ('hiit-class', 'HIIT Class', 'class', 'flow', 'other', 'duration', false, false, 0, false, NULL, 5820),
  ('bootcamp', 'Bootcamp', 'class', 'flow', 'other', 'duration', false, false, 0, false, NULL, 5830),
  ('crossfit-class', 'CrossFit Class', 'class', 'flow', 'other', 'duration', false, false, 0, false, '{"wod","crossfit"}'::text[], 5840),
  ('group-strength-class', 'Group Strength Class', 'class', 'flow', 'other', 'duration', false, false, 0, false, NULL, 5850),
  ('aqua-fitness', 'Aqua Fitness', 'class', 'flow', 'other', 'duration', false, false, 0, false, NULL, 5860),
  ('dance-class', 'Dance Class', 'class', 'flow', 'other', 'duration', false, false, 0, false, NULL, 5870),
  ('ballet-class', 'Ballet Class', 'class', 'flow', 'other', 'duration', false, false, 0, false, '{"ballet"}'::text[], 5880),
  ('contemporary-dance', 'Contemporary Dance', 'class', 'flow', 'other', 'duration', false, false, 0, false, NULL, 5890),
  ('reformer-sculpt', 'Reformer Sculpt', 'class', 'flow', 'other', 'duration', false, false, 0, false, NULL, 5900),
  ('basketball', 'Basketball', 'sport', 'sport', 'other', 'duration', false, false, 0, false, '{"hoops","ball"}'::text[], 5910),
  ('basketball-skills', 'Basketball Skills', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 5920),
  ('soccer', 'Soccer', 'sport', 'sport', 'other', 'duration', false, false, 0, false, '{"football"}'::text[], 5930),
  ('tennis', 'Tennis', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 5940),
  ('padel', 'Padel', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 5950),
  ('pickleball', 'Pickleball', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 5960),
  ('squash', 'Squash', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 5970),
  ('badminton', 'Badminton', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 5980),
  ('table-tennis', 'Table Tennis', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 5990),
  ('golf', 'Golf', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6000),
  ('volleyball', 'Volleyball', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6010),
  ('beach-volleyball', 'Beach Volleyball', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6020),
  ('baseball', 'Baseball', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6030),
  ('softball', 'Softball', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6040),
  ('american-football', 'American Football', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6050),
  ('rugby', 'Rugby', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6060),
  ('ice-hockey', 'Ice Hockey', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6070),
  ('field-hockey', 'Field Hockey', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6080),
  ('lacrosse', 'Lacrosse', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6090),
  ('cricket', 'Cricket', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6100),
  ('handball', 'Handball', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6110),
  ('ultimate-frisbee', 'Ultimate Frisbee', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6120),
  ('water-polo', 'Water Polo', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6130),
  ('boxing', 'Boxing', 'sport', 'sport', 'other', 'duration', false, false, 0, false, '{"boxing training"}'::text[], 6140),
  ('kickboxing', 'Kickboxing', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6150),
  ('muay-thai', 'Muay Thai', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6160),
  ('brazilian-jiu-jitsu', 'Brazilian Jiu-Jitsu', 'sport', 'sport', 'other', 'duration', false, false, 0, false, '{"bjj","jiu jitsu"}'::text[], 6170),
  ('judo', 'Judo', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6180),
  ('wrestling', 'Wrestling', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6190),
  ('karate', 'Karate', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6200),
  ('taekwondo', 'Taekwondo', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6210),
  ('martial-arts', 'Martial Arts', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6220),
  ('mma-training', 'MMA Training', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6230),
  ('fencing', 'Fencing', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6240),
  ('rock-climbing', 'Rock Climbing', 'sport', 'sport', 'other', 'duration', false, false, 0, false, '{"climbing"}'::text[], 6250),
  ('bouldering', 'Bouldering', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6260),
  ('surfing', 'Surfing', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6270),
  ('skateboarding', 'Skateboarding', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6280),
  ('snowboarding', 'Snowboarding', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6290),
  ('skiing', 'Skiing', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6300),
  ('cross-country-skiing', 'Cross-Country Skiing', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6310),
  ('mountain-biking', 'Mountain Biking', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6320),
  ('kayaking', 'Kayaking', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6330),
  ('paddleboarding', 'Paddleboarding', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6340),
  ('sailing', 'Sailing', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6350),
  ('horse-riding', 'Horse Riding', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6360),
  ('parkour', 'Parkour', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6370),
  ('gymnastics-practice', 'Gymnastics Practice', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6380),
  ('track-field', 'Track & Field', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6390),
  ('sports-practice', 'Sports Practice', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6400),
  ('pickup-game', 'Pickup Game', 'sport', 'sport', 'other', 'duration', false, false, 0, false, NULL, 6410),
  ('easy-run', 'Easy Run', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, NULL, 6420),
  ('long-run', 'Long Run', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, NULL, 6430),
  ('tempo-run', 'Tempo Run', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, NULL, 6440),
  ('interval-run', 'Interval Run', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, NULL, 6450),
  ('trail-run', 'Trail Run', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, NULL, 6460),
  ('bike-ride', 'Bike Ride', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, '{"cycling","bike"}'::text[], 6470),
  ('zone-2-bike', 'Zone 2 Bike', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, NULL, 6480),
  ('long-ride', 'Long Ride', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, NULL, 6490),
  ('swim-session', 'Swim Session', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, '{"swim"}'::text[], 6500),
  ('open-water-swim', 'Open-Water Swim', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, NULL, 6510),
  ('row-session', 'Row Session', 'endurance', 'conditioning', 'machine', 'duration', false, false, 0, false, '{"erg"}'::text[], 6520),
  ('hike', 'Hike', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, '{"hiking"}'::text[], 6530),
  ('ruck', 'Ruck', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, '{"rucking"}'::text[], 6540),
  ('walk', 'Walk', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, '{"walking"}'::text[], 6550),
  ('conditioning-session', 'Conditioning Session', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, NULL, 6560),
  ('zone-2-session', 'Zone 2 Session', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, NULL, 6570),
  ('sprint-session', 'Sprint Session', 'endurance', 'conditioning', 'other', 'duration', false, false, 0, false, NULL, 6580)
ON CONFLICT (id) DO UPDATE SET
  name               = excluded.name,
  category           = excluded.category,
  pattern            = excluded.pattern,
  equipment          = excluded.equipment,
  tracking_type      = excluded.tracking_type,
  takes_load         = excluded.takes_load,
  unilateral         = excluded.unilateral,
  bodyweight_factor  = excluded.bodyweight_factor,
  tracks_one_rep_max = excluded.tracks_one_rep_max,
  aliases            = COALESCE(excluded.aliases, exercises.aliases),
  sort_order         = excluded.sort_order,
  is_active          = true;
