/**
 * The last thing that touches a prompt before it leaves.
 *
 * The daily note is generated by a third-party model. We removed the member's
 * name from the prompt, which handles the field we control — and does nothing
 * about the field we don't: the member's own intention is free text, quoted
 * verbatim, and a member can write anything in it. "Ask Dr Nguyen about the
 * biopsy" is a sentence someone will eventually write into a wellness app, and
 * it would have gone out attached to that member's sleep and heart data.
 *
 * Two passes, doing different jobs:
 *
 *   scrubKnown  — exact-match removal of identifiers we HOLD. Not a heuristic:
 *                 we know this member's name and email, so we can look for
 *                 those exact strings and be certain. This is the strong one.
 *   redactFree  — pattern removal of identifiers we do not hold: emails, phone
 *                 numbers, URLs, handles. Necessarily incomplete, because the
 *                 general problem is unsolvable, and worth doing anyway
 *                 because the common cases are not the hard ones.
 *
 * Stated plainly so nobody over-trusts this: redactFree cannot catch a third
 * party's name written in plain prose. It is a reduction, not a guarantee. The
 * guarantee is scrubKnown, and it only covers the member themselves.
 */

const PATTERNS: { name: string; re: RegExp }[] = [
  { name: "email", re: /\b[\w.+-]+@[\w-]+\.[\w.]{2,}\b/gi },
  // Loose on purpose: a false positive costs a redacted number in a note
  // nobody reads twice, a false negative sends a phone number to a model.
  { name: "phone", re: /\+?\d[\d\s().-]{7,}\d/g },
  { name: "url", re: /\bhttps?:\/\/\S+|\bwww\.\S+/gi },
  { name: "handle", re: /(^|\s)@[a-z0-9_]{2,}/gi },
  // Anything long enough to be an account, policy or record number.
  { name: "long number", re: /\b\d{7,}\b/g },
];

export const REDACTED = "[redacted]";

/** Remove the identifier shapes we can recognise without knowing the person. */
export function redactFree(text: string): string {
  let out = text;
  for (const { re } of PATTERNS) out = out.replace(re, REDACTED);
  return out;
}

/**
 * Remove values we actually hold for this member.
 *
 * Case-insensitive and bounded by non-word characters so "Sam" does not gut
 * the word "same". Short values are skipped entirely — a two-letter name would
 * match inside half the words in the language, and a note full of [redacted]
 * is worse than the risk it removes.
 */
export function scrubKnown(text: string, identifiers: (string | null | undefined)[]): string {
  let out = text;
  for (const raw of identifiers) {
    const value = raw?.trim();
    if (!value || value.length < 3) continue;
    const escaped = value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    out = out.replace(new RegExp(`(^|\\W)${escaped}(?=\\W|$)`, "gi"), `$1${REDACTED}`);
  }
  return out;
}

/**
 * What a prompt still contains that it should not.
 *
 * Returns descriptions rather than throwing. A note that fails to generate is
 * a worse outcome for the member than a note generated from a prompt with one
 * unredacted phone number in it — so the caller redacts, records, and carries
 * on, and this list is what the tests assert on.
 */
export function findLeaks(
  text: string,
  identifiers: (string | null | undefined)[] = []
): string[] {
  const found: string[] = [];

  for (const { name, re } of PATTERNS) {
    // Fresh lastIndex: these are /g and RegExp is stateful, so reusing one
    // across calls silently skips matches on every other invocation.
    const probe = new RegExp(re.source, re.flags);
    if (probe.test(text)) found.push(name);
  }

  for (const raw of identifiers) {
    const value = raw?.trim();
    if (!value || value.length < 3) continue;
    const escaped = value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    if (new RegExp(`(^|\\W)${escaped}(?=\\W|$)`, "i").test(text)) {
      found.push("a known identifier for this member");
    }
  }

  return found;
}

/** Everything, in the order that makes the exact pass authoritative. */
export function sanitisePrompt(
  text: string,
  identifiers: (string | null | undefined)[] = []
): { prompt: string; redacted: string[] } {
  // Known values first. If a member wrote their own email in their intention,
  // it is caught here as a name-and-address pair rather than only as a
  // pattern, and the pattern pass then has nothing left to find.
  const scrubbed = redactFree(scrubKnown(text, identifiers));
  return { prompt: scrubbed, redacted: findLeaks(scrubbed, identifiers) };
}
