/**
 * The catalogue.
 *
 * ── Keyed, not titled ─────────────────────────────────────────────────────
 *
 * Every row has a `key` that never changes. Titles are copy: somebody will
 * improve "Magnesium before bed" to "Evening magnesium", and a loader matching
 * on title would insert a second row while every member tracking the first one
 * silently stopped matching. The key is the identity; everything else is
 * editable and expected to be edited.
 *
 * ── Two axes, kept apart ──────────────────────────────────────────────────
 *
 * `emphasis` is Yin or Yang — which half of a member's life this belongs to,
 * and the language they see. `load` is what it does to the body. They
 * correlate and they are not the same thing: a cold plunge is Yang and an
 * adaptive stressor, a magnesium capsule is Yin and merely supportive, and a
 * late night is neither Yin nor Yang and squarely depleting.
 *
 * ── Honest polarity ───────────────────────────────────────────────────────
 *
 * `polarity: "contextual"` on sauna, fasting and breathwork is not hedging.
 * Fasting sounds clearing and is a substantial physiological stressor; heat is
 * demand now and recovery later. Those items still carry an emphasis so they
 * appear on a card — they simply don't count as evidence of which way a day
 * leaned, which is the difference between a model and a label.
 *
 * ── What is deliberately not here ─────────────────────────────────────────
 *
 * Nothing that names a condition, promises an outcome, or reads as medical
 * advice. "Support your evening wind-down" is a practice; "lower your cortisol"
 * is a claim, and a claim in a catalogue is a claim in an app store review.
 */

import type { LoadClass, PriorityLevel, TerrainFit } from "../shared/models/loadClass.js";

export type CatalogueEntry = {
  key: string;
  title: string;
  short: string;
  emphasis: "yin" | "yang";
  tracking: string;
  /** Required for everything except `boolean`, forbidden on it. */
  target?: number;
  /** The health metric that answers this without anybody tapping. */
  metric?: string;
  load: LoadClass;
  /** The other true things about it. */
  tags?: LoadClass[];
  priority: PriorityLevel;
  polarity?: "strong" | "moderate" | "contextual";
  time?: "Morning" | "Midday" | "Evening" | "Anytime";
  maxPerWeek?: number;
  minutes?: number;
  fit?: TerrainFit;
  keywords: string[];
};

// ─── RESTORE — what gives capacity back ────────────────────────────────────

const RESTORE: CatalogueEntry[] = [
  // Sleep — the foundation everything else assumes
  {
    key: "sleep-duration",
    title: "Sleep 7–9 hours",
    short: "The one input nothing else compensates for.",
    emphasis: "yin",
    tracking: "hours",
    target: 8,
    metric: "sleepMinutes",
    load: "restorative",
    priority: "foundational",
    time: "Evening",
    fit: "restore",
    keywords: ["sleep", "rest", "bed", "hours", "recovery"],
  },
  {
    key: "consistent-bedtime",
    title: "Same bedtime, most nights",
    short: "A body that knows when night is coming falls asleep faster.",
    emphasis: "yin",
    tracking: "time-of-day",
    target: 1380,
    load: "restorative",
    priority: "foundational",
    time: "Evening",
    fit: "restore",
    keywords: ["bedtime", "sleep", "routine", "consistency", "schedule"],
  },
  {
    key: "screens-off-before-bed",
    title: "Screens down an hour before bed",
    short: "The last hour decides the first three.",
    emphasis: "yin",
    tracking: "boolean",
    load: "restorative",
    priority: "supportive",
    time: "Evening",
    fit: "restore",
    keywords: ["screens", "phone", "blue light", "bed", "evening"],
  },
  {
    key: "dark-cool-room",
    title: "Dark, cool room",
    short: "Blackout, and a few degrees cooler than feels obvious.",
    emphasis: "yin",
    tracking: "boolean",
    load: "restorative",
    priority: "supportive",
    time: "Evening",
    fit: "restore",
    keywords: ["dark", "cool", "bedroom", "temperature", "sleep"],
  },
  {
    key: "no-caffeine-after-noon",
    title: "No caffeine after midday",
    short: "Half of a morning coffee is still in you at bedtime.",
    emphasis: "yin",
    tracking: "boolean",
    load: "supportive",
    priority: "foundational",
    time: "Midday",
    fit: "restore",
    keywords: ["caffeine", "coffee", "cutoff", "sleep", "afternoon"],
  },
  {
    key: "no-alcohol-tonight",
    title: "Alcohol-free night",
    short: "It shortens the time to sleep and takes the depth away.",
    emphasis: "yin",
    tracking: "boolean",
    load: "supportive",
    priority: "supportive",
    time: "Evening",
    fit: "restore",
    keywords: ["alcohol", "drink", "sober", "night", "sleep"],
  },
  {
    key: "wind-down-ritual",
    title: "Evening downshift",
    short: "Ten minutes of nothing, on purpose, before the day is over.",
    emphasis: "yin",
    tracking: "minutes",
    target: 10,
    load: "restorative",
    priority: "supportive",
    time: "Evening",
    minutes: 10,
    fit: "restore",
    keywords: ["downshift", "wind down", "evening", "relax", "calm"],
  },
  {
    key: "sleep-deep-minutes",
    title: "Deep sleep",
    short: "The part of the night the body rebuilds in.",
    emphasis: "yin",
    tracking: "minutes",
    target: 75,
    metric: "sleepDeepMinutes",
    load: "restorative",
    priority: "supportive",
    fit: "restore",
    keywords: ["deep sleep", "slow wave", "recovery", "sleep"],
  },

  // Minerals and supplements
  {
    key: "magnesium-evening",
    title: "Magnesium at night",
    short: "Glycinate or malate, with the last meal.",
    emphasis: "yin",
    tracking: "boolean",
    load: "supportive",
    priority: "supportive",
    time: "Evening",
    fit: "restore",
    keywords: ["magnesium", "mineral", "glycinate", "supplement", "night"],
  },
  {
    key: "electrolytes-daily",
    title: "Electrolytes",
    short: "Sodium, potassium and magnesium — water without them does less.",
    emphasis: "yin",
    tracking: "servings",
    target: 1,
    load: "supportive",
    priority: "foundational",
    time: "Morning",
    fit: "either",
    keywords: ["electrolytes", "salt", "sodium", "potassium", "hydration", "minerals"],
  },
  {
    key: "vitamin-d",
    title: "Vitamin D",
    short: "With fat, and with breakfast rather than at night.",
    emphasis: "yin",
    tracking: "boolean",
    load: "supportive",
    priority: "supportive",
    time: "Morning",
    fit: "either",
    keywords: ["vitamin d", "d3", "supplement", "sunshine vitamin"],
  },
  {
    key: "omega-3",
    title: "Omega-3",
    short: "Fish oil or the fish itself.",
    emphasis: "yin",
    tracking: "boolean",
    load: "supportive",
    priority: "supportive",
    time: "Anytime",
    fit: "either",
    keywords: ["omega", "fish oil", "epa", "dha", "supplement"],
  },
  {
    key: "creatine-daily",
    title: "Creatine",
    short: "Five grams, every day, timing irrelevant.",
    emphasis: "yang",
    tracking: "grams",
    target: 5,
    load: "supportive",
    priority: "supportive",
    time: "Anytime",
    fit: "build",
    keywords: ["creatine", "monohydrate", "supplement", "strength"],
  },
  {
    key: "zinc-evening",
    title: "Zinc",
    short: "Away from calcium, and never on an empty stomach.",
    emphasis: "yin",
    tracking: "boolean",
    load: "supportive",
    priority: "advanced",
    time: "Evening",
    fit: "either",
    keywords: ["zinc", "mineral", "supplement"],
  },
  {
    key: "collagen-daily",
    title: "Collagen",
    short: "With vitamin C, ideally before loading the tissue.",
    emphasis: "yin",
    tracking: "grams",
    target: 15,
    load: "supportive",
    priority: "advanced",
    time: "Morning",
    fit: "either",
    keywords: ["collagen", "joints", "tendon", "skin", "supplement"],
  },

  // Hydration and digestion
  {
    key: "water-intake",
    title: "Water",
    short: "Through the day, not all at once in the evening.",
    emphasis: "yin",
    tracking: "litres",
    target: 3,
    metric: "waterMl",
    load: "supportive",
    priority: "foundational",
    time: "Anytime",
    fit: "either",
    keywords: ["water", "hydration", "drink", "fluids", "litres"],
  },
  {
    key: "eat-sitting-down",
    title: "Eat sitting down, not at a screen",
    short: "Digestion is a rest-state process. Standing over a laptop isn't one.",
    emphasis: "yin",
    tracking: "meals",
    target: 2,
    load: "supportive",
    priority: "supportive",
    fit: "restore",
    keywords: ["eating", "digestion", "meal", "mindful", "screen"],
  },
  {
    key: "chew-properly",
    title: "Chew properly",
    short: "The first stage of digestion is the only one you control.",
    emphasis: "yin",
    tracking: "meals",
    target: 2,
    load: "supportive",
    priority: "supportive",
    fit: "restore",
    keywords: ["chew", "digestion", "eating", "slow"],
  },
  {
    key: "fibre-target",
    title: "Fibre",
    short: "From plants, across the day.",
    emphasis: "yin",
    tracking: "grams",
    target: 30,
    load: "supportive",
    priority: "supportive",
    fit: "either",
    keywords: ["fibre", "fiber", "gut", "plants", "digestion"],
  },
  {
    key: "fermented-food",
    title: "Something fermented",
    short: "Kefir, kraut, kimchi, yoghurt — one of them, most days.",
    emphasis: "yin",
    tracking: "servings",
    target: 1,
    load: "supportive",
    priority: "advanced",
    fit: "restore",
    keywords: ["fermented", "gut", "probiotic", "kefir", "kimchi", "sauerkraut"],
  },
  {
    key: "eating-window-close",
    title: "Stop eating three hours before bed",
    short: "A body digesting is a body not sleeping.",
    emphasis: "yin",
    tracking: "boolean",
    load: "supportive",
    priority: "supportive",
    time: "Evening",
    fit: "restore",
    keywords: ["eating window", "last meal", "fasting", "evening", "digestion"],
  },

  // Nervous system
  {
    key: "breathwork-downshift",
    title: "Slow breathing",
    short: "Longer out than in. Five minutes changes the state you're in.",
    emphasis: "yin",
    tracking: "minutes",
    target: 5,
    metric: "mindfulnessMinutes",
    load: "restorative",
    priority: "supportive",
    polarity: "contextual",
    time: "Anytime",
    minutes: 5,
    fit: "restore",
    keywords: ["breath", "breathing", "breathwork", "downshift", "calm", "vagus"],
  },
  {
    key: "meditation-sit",
    title: "Sit still",
    short: "No technique required. The stillness is the practice.",
    emphasis: "yin",
    tracking: "minutes",
    target: 10,
    metric: "mindfulnessMinutes",
    load: "restorative",
    priority: "supportive",
    time: "Morning",
    minutes: 10,
    fit: "restore",
    keywords: ["meditation", "stillness", "mindfulness", "sit", "quiet"],
  },
  {
    key: "nsdr",
    title: "Non-sleep deep rest",
    short: "Twenty minutes lying down, awake. Not a nap and not nothing.",
    emphasis: "yin",
    tracking: "minutes",
    target: 20,
    load: "restorative",
    priority: "advanced",
    time: "Midday",
    minutes: 20,
    fit: "restore",
    keywords: ["nsdr", "yoga nidra", "rest", "nap", "recovery"],
  },
  {
    key: "no-phone-first-hour",
    title: "No phone for the first hour",
    short: "What you do first sets what the day feels like.",
    emphasis: "yin",
    tracking: "boolean",
    load: "restorative",
    priority: "supportive",
    time: "Morning",
    fit: "restore",
    keywords: ["phone", "morning", "screen", "first hour", "attention"],
  },
  {
    key: "time-outdoors",
    title: "Time outside",
    short: "Not exercise. Just outside.",
    emphasis: "yin",
    tracking: "minutes",
    target: 30,
    load: "restorative",
    priority: "supportive",
    polarity: "moderate",
    time: "Anytime",
    minutes: 30,
    fit: "either",
    keywords: ["outside", "outdoors", "nature", "fresh air", "walk"],
  },
  {
    key: "journal-clear",
    title: "Write it down",
    short: "Whatever is circling. On paper it stops circling.",
    emphasis: "yin",
    tracking: "boolean",
    load: "restorative",
    priority: "advanced",
    time: "Evening",
    fit: "restore",
    keywords: ["journal", "write", "brain dump", "clarity", "reflection"],
  },
  {
    key: "one-honest-conversation",
    title: "One honest conversation",
    short: "The thing you've been not saying.",
    emphasis: "yin",
    tracking: "boolean",
    load: "restorative",
    priority: "advanced",
    fit: "restore",
    keywords: ["conversation", "honest", "connection", "relationship", "talk"],
  },
  {
    key: "no-work-after-hour",
    title: "Work ends when you said it would",
    short: "An open laptop at 10pm is a nervous system that never clocks off.",
    emphasis: "yin",
    tracking: "boolean",
    load: "restorative",
    priority: "supportive",
    time: "Evening",
    fit: "restore",
    keywords: ["work", "boundary", "evening", "switch off", "laptop"],
  },

  // Recovery modalities — the honest ones
  {
    key: "sauna-session",
    title: "Sauna",
    short: "Heat is demand now and recovery later. Both are true.",
    emphasis: "yin",
    tracking: "minutes",
    target: 20,
    load: "adaptive-stressor",
    tags: ["restorative"],
    priority: "advanced",
    polarity: "contextual",
    maxPerWeek: 4,
    minutes: 20,
    fit: "either",
    keywords: ["sauna", "heat", "hot", "recovery", "sweat"],
  },
  {
    key: "cold-exposure",
    title: "Cold exposure",
    short: "A real stressor with a real return. Not a substitute for sleep.",
    emphasis: "yang",
    tracking: "minutes",
    target: 3,
    load: "adaptive-stressor",
    priority: "advanced",
    polarity: "contextual",
    maxPerWeek: 4,
    minutes: 3,
    fit: "build",
    keywords: ["cold", "plunge", "ice", "shower", "exposure"],
  },
  {
    key: "fascia-work",
    title: "Fascia work",
    short: "Slow, and on the tissue that's actually stuck.",
    emphasis: "yin",
    tracking: "minutes",
    target: 15,
    load: "restorative",
    priority: "supportive",
    minutes: 15,
    fit: "restore",
    keywords: ["fascia", "roll", "release", "tissue", "myofascial"],
  },
  {
    key: "stretch-evening",
    title: "Stretch before bed",
    short: "Long holds. Nothing that raises your heart rate.",
    emphasis: "yin",
    tracking: "minutes",
    target: 10,
    load: "restorative",
    priority: "supportive",
    time: "Evening",
    minutes: 10,
    fit: "restore",
    keywords: ["stretch", "flexibility", "evening", "yin", "mobility"],
  },
  {
    key: "full-rest-day",
    title: "A day off, properly",
    short: "Not a light day. A day off.",
    emphasis: "yin",
    tracking: "boolean",
    load: "restorative",
    priority: "foundational",
    maxPerWeek: 3,
    fit: "restore",
    keywords: ["rest day", "off", "recovery", "deload", "break"],
  },
  {
    key: "hrv-watch",
    title: "Heart rate variability",
    short: "Read, never entered. What your body says about yesterday.",
    emphasis: "yin",
    tracking: "count",
    target: 50,
    metric: "heartRateVariability",
    load: "neutral",
    priority: "supportive",
    polarity: "contextual",
    fit: "either",
    keywords: ["hrv", "heart rate variability", "recovery", "nervous system"],
  },
  {
    key: "resting-heart-rate",
    title: "Resting heart rate",
    short: "Slow drift up is the earliest thing a body says out loud.",
    emphasis: "yin",
    tracking: "count",
    target: 55,
    metric: "restingHeartRate",
    load: "neutral",
    priority: "supportive",
    polarity: "contextual",
    fit: "either",
    keywords: ["resting heart rate", "rhr", "pulse", "recovery"],
  },
];

// ─── BUILD — what asks for capacity ────────────────────────────────────────

const BUILD: CatalogueEntry[] = [
  // Food
  {
    key: "protein-target",
    title: "Protein",
    short: "Across the day, not all in the evening.",
    emphasis: "yang",
    tracking: "grams",
    target: 160,
    load: "building",
    priority: "foundational",
    fit: "build",
    keywords: ["protein", "grams", "macro", "muscle", "food"],
  },
  {
    key: "protein-at-breakfast",
    title: "Protein at breakfast",
    short: "Thirty grams before ten. It changes the whole day's appetite.",
    emphasis: "yang",
    tracking: "grams",
    target: 30,
    load: "building",
    priority: "supportive",
    time: "Morning",
    fit: "build",
    keywords: ["protein", "breakfast", "morning", "macro"],
  },
  {
    key: "carb-target",
    title: "Carbohydrate",
    short: "Fuel. Around the training, not away from it.",
    emphasis: "yang",
    tracking: "grams",
    target: 200,
    load: "building",
    priority: "supportive",
    fit: "build",
    keywords: ["carbs", "carbohydrate", "fuel", "macro", "energy"],
  },
  {
    key: "calorie-intake",
    title: "Calories",
    short: "The number under every other number.",
    emphasis: "yang",
    tracking: "calories",
    target: 2400,
    metric: "dietaryCalories",
    load: "neutral",
    priority: "supportive",
    polarity: "contextual",
    fit: "either",
    keywords: ["calories", "energy", "intake", "food", "kcal"],
  },
  {
    key: "eat-real-food",
    title: "Meals you cooked",
    short: "Anything you made yourself counts.",
    emphasis: "yang",
    tracking: "meals",
    target: 2,
    load: "supportive",
    priority: "supportive",
    fit: "either",
    keywords: ["cook", "real food", "meals", "home", "whole food"],
  },
  {
    key: "plants-variety",
    title: "Different plants",
    short: "Count the kinds, not the grams.",
    emphasis: "yang",
    tracking: "count",
    target: 6,
    load: "supportive",
    priority: "supportive",
    fit: "either",
    keywords: ["plants", "vegetables", "variety", "gut", "diversity"],
  },

  // Movement — daily
  {
    key: "step-count",
    title: "Steps",
    short: "The base of everything else, and the easiest thing to lose.",
    emphasis: "yang",
    tracking: "steps",
    target: 10000,
    metric: "steps",
    load: "building",
    priority: "foundational",
    fit: "build",
    keywords: ["steps", "walk", "walking", "movement", "neat"],
  },
  {
    key: "zone-two",
    title: "Easy aerobic work",
    short: "Nose-breathing pace. Boring on purpose.",
    emphasis: "yang",
    tracking: "minutes",
    target: 45,
    metric: "exerciseMinutes",
    load: "building",
    priority: "foundational",
    minutes: 45,
    maxPerWeek: 5,
    fit: "build",
    keywords: ["zone 2", "aerobic", "cardio", "easy", "base", "endurance"],
  },
  {
    key: "strength-session",
    title: "Lift something heavy",
    short: "The single most protective thing on this list.",
    emphasis: "yang",
    tracking: "boolean",
    load: "building",
    tags: ["adaptive-stressor"],
    priority: "foundational",
    maxPerWeek: 5,
    fit: "build",
    keywords: ["strength", "lift", "weights", "resistance", "gym", "training"],
  },
  {
    key: "intervals",
    title: "Hard intervals",
    short: "Short, genuinely hard, and not every day.",
    emphasis: "yang",
    tracking: "minutes",
    target: 20,
    load: "adaptive-stressor",
    tags: ["building"],
    priority: "advanced",
    maxPerWeek: 3,
    minutes: 20,
    fit: "build",
    keywords: ["intervals", "hiit", "sprint", "vo2", "hard", "conditioning"],
  },
  {
    key: "movement-breaks",
    title: "Get up and move",
    short: "Once an hour beats one long session at six.",
    emphasis: "yang",
    tracking: "count",
    target: 5,
    load: "supportive",
    priority: "supportive",
    fit: "either",
    keywords: ["movement break", "stand", "desk", "sitting", "hourly"],
  },
  {
    key: "mobility-work",
    title: "Mobility",
    short: "Range you can control, not range you can reach.",
    emphasis: "yang",
    tracking: "minutes",
    target: 15,
    load: "restorative",
    tags: ["building"],
    priority: "supportive",
    polarity: "moderate",
    minutes: 15,
    fit: "either",
    keywords: ["mobility", "range", "joints", "flexibility", "movement"],
  },
  {
    key: "carry-something-heavy",
    title: "Carry something heavy",
    short: "Grip, trunk and the whole posterior chain, for free.",
    emphasis: "yang",
    tracking: "minutes",
    target: 5,
    load: "building",
    priority: "advanced",
    maxPerWeek: 4,
    minutes: 5,
    fit: "build",
    keywords: ["carry", "farmer", "loaded", "grip", "weight"],
  },
  {
    key: "hang",
    title: "Hang from a bar",
    short: "A minute a day, cumulative. Shoulders, grip, spine.",
    emphasis: "yang",
    tracking: "minutes",
    target: 1,
    load: "building",
    priority: "advanced",
    minutes: 1,
    fit: "build",
    keywords: ["hang", "bar", "shoulders", "grip", "decompress"],
  },
  {
    key: "walk-after-meals",
    title: "Walk after eating",
    short: "Ten minutes does more than the length suggests.",
    emphasis: "yang",
    tracking: "count",
    target: 2,
    load: "supportive",
    priority: "supportive",
    polarity: "moderate",
    fit: "either",
    keywords: ["walk", "after meal", "glucose", "digestion", "post-meal"],
  },
  {
    key: "stairs",
    title: "Take the stairs",
    short: "Flights, counted by the phone in your pocket.",
    emphasis: "yang",
    tracking: "count",
    target: 10,
    metric: "flightsClimbed",
    load: "building",
    priority: "supportive",
    fit: "build",
    keywords: ["stairs", "flights", "climb", "incline"],
  },
  {
    key: "active-calories",
    title: "Active calories",
    short: "What the day actually cost you, not what you planned.",
    emphasis: "yang",
    tracking: "calories",
    target: 600,
    metric: "activeCalories",
    load: "building",
    priority: "supportive",
    polarity: "moderate",
    fit: "build",
    keywords: ["active calories", "burn", "expenditure", "move"],
  },
  {
    key: "distance-covered",
    title: "Distance on your own legs",
    short: "Walked, run or hiked — the phone doesn't care which.",
    emphasis: "yang",
    tracking: "count",
    target: 8000,
    metric: "distanceMeters",
    load: "building",
    priority: "supportive",
    polarity: "moderate",
    fit: "build",
    keywords: ["distance", "metres", "km", "walk", "run", "hike"],
  },

  // Light and rhythm
  {
    key: "morning-light",
    title: "Morning light",
    short: "Outside, within an hour of waking, before the sunglasses.",
    emphasis: "yang",
    tracking: "minutes",
    target: 10,
    load: "supportive",
    priority: "foundational",
    time: "Morning",
    minutes: 10,
    fit: "either",
    keywords: ["light", "sun", "morning", "circadian", "daylight", "sunlight"],
  },
  {
    key: "midday-sun",
    title: "Midday sun on skin",
    short: "Short and deliberate, not an afternoon of it.",
    emphasis: "yang",
    tracking: "minutes",
    target: 15,
    load: "supportive",
    priority: "supportive",
    time: "Midday",
    minutes: 15,
    fit: "either",
    keywords: ["sun", "sunlight", "vitamin d", "skin", "midday"],
  },
  {
    key: "sunset-light",
    title: "See the light go",
    short: "The evening signal is as real as the morning one.",
    emphasis: "yin",
    tracking: "boolean",
    load: "supportive",
    priority: "advanced",
    time: "Evening",
    fit: "restore",
    keywords: ["sunset", "evening light", "circadian", "dusk"],
  },

  // Practice and edge
  {
    key: "train-a-skill",
    title: "Practise something you're bad at",
    short: "A skill, not a workout. The nervous system counts it differently.",
    emphasis: "yang",
    tracking: "minutes",
    target: 20,
    load: "building",
    priority: "advanced",
    minutes: 20,
    fit: "build",
    keywords: ["skill", "practice", "learn", "coordination", "technique"],
  },
  {
    key: "sport-or-play",
    title: "Play something",
    short: "A sport, a game, anything with somebody else in it.",
    emphasis: "yang",
    tracking: "boolean",
    load: "building",
    tags: ["adaptive-stressor"],
    priority: "advanced",
    maxPerWeek: 4,
    fit: "build",
    keywords: ["sport", "play", "game", "team", "fun"],
  },
  {
    key: "fasted-window",
    title: "Longer eating gap",
    short: "Sounds clearing, is a real stressor. Not on a heavy week.",
    emphasis: "yang",
    tracking: "hours",
    target: 16,
    load: "adaptive-stressor",
    priority: "advanced",
    polarity: "contextual",
    maxPerWeek: 4,
    fit: "either",
    keywords: ["fasting", "fast", "eating window", "intermittent", "16:8"],
  },
  {
    key: "hard-thing-first",
    title: "The hard thing, first",
    short: "The one you've been moving down the list.",
    emphasis: "yang",
    tracking: "boolean",
    load: "neutral",
    priority: "supportive",
    time: "Morning",
    fit: "build",
    keywords: ["hard thing", "priority", "focus", "discipline", "first"],
  },
  {
    key: "deep-work-block",
    title: "One uninterrupted block",
    short: "Ninety minutes, nothing else open.",
    emphasis: "yang",
    tracking: "minutes",
    target: 90,
    load: "building",
    priority: "advanced",
    time: "Morning",
    minutes: 90,
    fit: "build",
    keywords: ["deep work", "focus", "block", "concentration", "uninterrupted"],
  },
  {
    key: "weigh-in",
    title: "Weigh in",
    short: "Same time, same conditions. The trend is the data, not the day.",
    emphasis: "yang",
    tracking: "count",
    target: 80,
    metric: "weightKg",
    load: "neutral",
    priority: "supportive",
    polarity: "contextual",
    time: "Morning",
    fit: "either",
    keywords: ["weight", "scale", "weigh", "body", "trend"],
  },
];

export const CATALOGUE: CatalogueEntry[] = [...RESTORE, ...BUILD];
