/**
 * One commit, one web application, two shells.
 *
 * ── The failure this exists to make impossible ────────────────────────────
 *
 * `build-aab.sh` runs `npm run build:client` before it syncs Android. That is
 * correct on its own and wrong in a pair: cut iOS first and the archive
 * consumes one build of the client; then the Android script makes another and
 * ships that. Two applications from one SHA.
 *
 * It happened. iOS 34's first archive carried four asset filenames that were
 * nowhere in `dist`, because the AAB script had rebuilt the client underneath
 * it. Both were built from the same tree and neither could be shown to match
 * the other — which is the whole of artifact provenance gone.
 *
 * The client is reproducible now (see `builtAt` in vite.config.ts), so two
 * builds of one tree are byte-identical and the pair would survive a rebuild.
 * That is a reason this check passes, not a reason to stop making it: a
 * reproducible build is a property that can regress, and this is what would
 * notice.
 *
 * ── Why content and not filenames ─────────────────────────────────────────
 *
 * Vite's names carry a content hash, so equal names are strong evidence. They
 * are not proof: `cap sync` copies, and a copy can be truncated, partial, or
 * left over from a previous run under a name that still matches. Every file
 * is hashed, and the set has to match exactly — no extras on either side,
 * which is how a stale asset from an older build gets caught.
 *
 *   node script/native-parity.mjs
 */
import { createHash } from "node:crypto";
import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";

const ROOT = process.cwd();
const CANON = "dist/public";
const SHELLS = [
  ["iOS", "ios/App/App/public"],
  ["Android", "android/app/src/main/assets/public"],
];

/**
 * Files Capacitor writes into the shell that were never in `dist`.
 *
 * Named rather than pattern-matched, and kept short on purpose: the value of
 * this check is that anything in a shell and not in the build is a finding,
 * so every exemption has to be one somebody decided to make. These two are
 * generated by `cap sync` from the installed plugins and have no source in
 * the web build at all.
 */
const INJECTED = new Set(["cordova.js", "cordova_plugins.js"]);

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

/** Every file under a tree, as `relative path → sha256`. */
function fingerprint(root) {
  const base = join(ROOT, root);
  if (!existsSync(base)) return null;
  const map = new Map();
  for (const file of walk(base)) {
    map.set(
      relative(base, file).split(sep).join("/"),
      createHash("sha256").update(readFileSync(file)).digest("hex"),
    );
  }
  return map;
}

const canon = fingerprint(CANON);
if (!canon) {
  console.error(`\n  no ${CANON} — run the client build first\n`);
  process.exit(1);
}
if (canon.size === 0) {
  console.error(`\n  ${CANON} is empty\n`);
  process.exit(1);
}

let bad = false;
for (const [name, dir] of SHELLS) {
  const theirs = fingerprint(dir);
  if (!theirs) {
    console.error(`  ${name.padEnd(8)} no ${dir} — has \`npx cap sync\` run?`);
    bad = true;
    continue;
  }

  const missing = [...canon.keys()].filter((f) => !theirs.has(f));
  const extra = [...theirs.keys()].filter((f) => !canon.has(f) && !INJECTED.has(f));
  const changed = [...canon.entries()]
    .filter(([f, h]) => theirs.has(f) && theirs.get(f) !== h)
    .map(([f]) => f);

  if (missing.length || extra.length || changed.length) {
    bad = true;
    console.error(`  ${name.padEnd(8)} does NOT match ${CANON}`);
    const say = (label, list) => {
      if (!list.length) return;
      console.error(`      ${label}: ${list.slice(0, 6).join(", ")}${list.length > 6 ? ` (+${list.length - 6})` : ""}`);
    };
    say("missing", missing);
    say("stale/extra", extra);
    say("different content", changed);
  } else {
    console.error(`  ${name.padEnd(8)} matches — ${theirs.size} files, identical bytes`);
  }
}

if (bad) {
  console.error(`
  A release pair must contain one web application.

      npm run build           # once
      npx cap sync            # both shells, from that one build
      node script/native-parity.mjs
`);
  process.exit(1);
}
console.error(`\n  ✓ one web application in both shells (${canon.size} files)\n`);
