/**
 * Does every field in the admin actually reach the database?
 *
 * This is the oldest complaint about this back office and the most expensive
 * one to find by hand: a box you can type into that saves nothing. It has no
 * symptom at save time. The request returns 200, the dialog closes, the toast
 * says saved — and the value is simply gone when you reopen the record. The
 * only way anyone ever caught it was doing exactly what should never be
 * necessary: filling in a form, then going to the database to check.
 *
 * There are three links in the chain and a break in any one of them looks
 * identical from the outside:
 *
 *   1. the form field the author types into
 *   2. the zod schema the route parses the request body with
 *   3. the column in Postgres
 *
 * A field in (1) missing from (2) is stripped by `.parse()` and never reaches
 * the insert. A field in (3) missing from (1) can't be authored at all — and
 * worse, if the form writes the record without it, an edit-and-save blanks
 * whatever was there. TypeScript catches none of this: every layer is
 * internally consistent, they just disagree with each other.
 *
 * So this walks the actual dialog source for `form.x` reads, the actual zod
 * schema for its keys, and the actual Drizzle table for its columns, and
 * requires the three to agree. Anything deliberately not authored has to be
 * named in EXEMPT with a reason, which turns "I forgot" into "I decided".
 *
 * Run: tsx script/test-admin-fields.ts
 */

import { readFileSync } from "node:fs";
import { getTableColumns } from "drizzle-orm";
import {
  wellnessRoutines,
  routineHabits,
  insertWellnessRoutineSchema,
  insertRoutineHabitSchema,
} from "../shared/schema.js";

let passed = 0;
let failed = 0;

function check(name: string, cond: boolean, detail?: string) {
  if (cond) {
    passed++;
  } else {
    failed++;
    console.log(`  ✗ ${name}${detail ? ` — ${detail}` : ""}`);
  }
}

function section(title: string) {
  console.log(`\n${title}`);
}

const ADMIN = readFileSync("client/src/pages/AdminPortal.tsx", "utf8");

/**
 * Every `form.x` read inside one dialog function.
 *
 * Reading the source rather than a hand-kept list is the entire point: a list
 * of "fields the form has" is one more thing that can drift from the form,
 * and drift is the bug being tested for.
 */
function formFields(fnName: string): Set<string> {
  const start = ADMIN.indexOf(`function ${fnName}(`);
  if (start < 0) throw new Error(`${fnName} not found in AdminPortal.tsx`);

  // To the next top-level `function ` declaration, which is where this one ends.
  const after = ADMIN.indexOf("\nfunction ", start + 1);
  const body = ADMIN.slice(start, after < 0 ? undefined : after);

  const fields = new Set<string>();
  for (const m of body.matchAll(/\bform\.(\w+)/g)) fields.add(m[1]);
  // `set("x", …)` covers the write side, which for a checkbox or a Select is
  // the only place the name appears.
  for (const m of body.matchAll(/\bset\(\s*"(\w+)"/g)) fields.add(m[1]);
  return fields;
}

/**
 * Columns nobody authors in the dialog, and why. A column may only be here
 * for a reason that is true — "we forgot" is not one of them.
 */
const EXEMPT: Record<string, Record<string, string>> = {
  wellness_routines: {
    id: "slug, derived from the name by the server on create",
    createdAt: "set by the database",
    updatedAt: "set by the server on write",
    copyBlockId: "reserved for an external CMS reference; nothing reads it yet",
  },
  routine_habits: {
    id: "generated by the database",
    createdAt: "set by the database",
    updatedAt: "set by the server on write",
    copyBlockId: "reserved for an external CMS reference; nothing reads it yet",
    isFree: "gating lives on the routine's tier, not per habit",
    description: "legacy duplicate of shortDescription; kept for old rows only",
    intensity:
      "deliberately no longer asked for — nothing downstream serves a lite " +
      "vs intense variant, so it was a required choice with no consequence. " +
      "Column stays NOT NULL DEFAULT 'lite' so inserts are unaffected.",
  },
};

console.log("Admin fields reach the database");

const SUBJECTS = [
  {
    label: "Routine",
    table: wellnessRoutines,
    tableName: "wellness_routines",
    schema: insertWellnessRoutineSchema,
    dialog: "RoutineFormDialog",
  },
  {
    label: "Habit",
    table: routineHabits,
    tableName: "routine_habits",
    schema: insertRoutineHabitSchema,
    dialog: "HabitFormDialog",
  },
] as const;

for (const s of SUBJECTS) {
  section(`${s.label} — ${s.dialog} ↔ ${s.tableName}`);

  const columns = new Set(Object.keys(getTableColumns(s.table)));
  const schemaKeys = new Set(Object.keys(s.schema.shape));
  const fields = formFields(s.dialog);
  const exempt = EXEMPT[s.tableName] ?? {};

  // ── Link 1 → 2. A field the schema doesn't know is silently dropped by
  // .parse(), which is the quietest way to lose a value in the whole stack.
  const notInSchema = [...fields].filter((f) => !schemaKeys.has(f));
  check(
    `every form field survives ${s.label.toLowerCase()} validation`,
    notInSchema.length === 0,
    notInSchema.length ? `dropped by .parse(): ${notInSchema.join(", ")}` : "",
  );

  // ── Link 2 → 3. drizzle-zod derives the schema from the table, so a
  // mismatch here means someone hand-edited one of them.
  const schemaNotColumn = [...schemaKeys].filter((k) => !columns.has(k));
  check(
    `every ${s.label.toLowerCase()} schema key is a real column`,
    schemaNotColumn.length === 0,
    schemaNotColumn.join(", "),
  );

  // ── Link 3 → 1. A column with no field can't be authored, and a form that
  // writes the whole row without it blanks it on the next edit-and-save.
  const unauthored = [...columns].filter((c) => !fields.has(c) && !exempt[c]);
  check(
    `every ${s.label.toLowerCase()} column is either editable or explicitly exempt`,
    unauthored.length === 0,
    unauthored.length ? `no field for: ${unauthored.join(", ")}` : "",
  );

  // An exemption for a column that no longer exists is a stale note that will
  // outlive its reason and quietly excuse a future column of the same name.
  const staleExempt = Object.keys(exempt).filter((c) => !columns.has(c));
  check(`no stale exemptions for ${s.tableName}`, staleExempt.length === 0, staleExempt.join(", "));

  // An exemption for a field the form *does* have means the note is wrong
  // about the form, and the reason it gives is no longer being relied on.
  const contradicted = Object.keys(exempt).filter((c) => fields.has(c));
  check(
    `no exemption contradicts the ${s.dialog}`,
    contradicted.length === 0,
    contradicted.join(", "),
  );

  console.log(
    `  ${fields.size} fields, ${columns.size} columns, ${Object.keys(exempt).length} exempt`,
  );
}

/* ── The specific fields the old back office had ─────────────────────────── */

section("Parity with the previous admin");

{
  const routineFields = formFields("RoutineFormDialog");
  const habitFields = formFields("HabitFormDialog");

  // Everything the screenshots of the old Manage Routines / Manage Habits
  // forms could set. Listed explicitly because "the schema and the form
  // agree" is satisfied perfectly well by both of them being incomplete.
  const OLD_ROUTINE = [
    "name", "coverImageUrl", "description", "goal", "whoIsThisFor",
    "whatToExpect", "expectedResults", "goalDescription", "searchKeywords",
    "sortOrder", "isFeatured", "durationDays", "category", "icon", "color",
    "terrainTags",
  ];
  const OLD_HABIT = [
    "title", "routineId", "shortDescription", "detailedDescription",
    "scienceExplanation", "tips", "expectToNotice", "cadence",
    "durationMinutes", "icon", "recommendedTime", "dayStart", "dayEnd",
    "orderIndex", "terrainTags", "searchKeywords",
  ];

  const missingR = OLD_ROUTINE.filter((f) => f !== "routineId" && !routineFields.has(f));
  check("the routine form has everything the old one had", missingR.length === 0, missingR.join(", "));

  // routineId is set by the picker outside `form.` reads, so check the source
  // for the control itself rather than the form state.
  const missingH = OLD_HABIT.filter((f) => f !== "routineId" && !habitFields.has(f));
  check("the habit form has everything the old one had", missingH.length === 0, missingH.join(", "));
  check("the habit form still has the routine picker", ADMIN.includes('set("routineId"'));

  // The one thing deliberately dropped, and the meal-relative times added.
  check("intensity is no longer asked for", !habitFields.has("intensity"));
  check("recommended time offers pre-meal", ADMIN.includes('value="Pre-meal"'));
  check("recommended time offers post-meal", ADMIN.includes('value="Post-meal"'));
}

/* ── The tag columns are arrays, and the form holds text ─────────────────── */

section("Tag conversion");

{
  // text[] columns fed from comma-separated inputs. Sending the raw string
  // fails validation; sending [] would overwrite real tags with "none set".
  const parsedR = insertWellnessRoutineSchema.safeParse({
    id: "x", name: "n", description: "d", category: "Sleep",
    terrainTags: "sleep, gut",
  });
  check("a raw string is rejected for a text[] column", !parsedR.success);

  const ok = insertWellnessRoutineSchema.safeParse({
    id: "x", name: "n", description: "d", category: "Sleep",
    terrainTags: ["sleep", "gut"], searchKeywords: null,
  });
  check("an array is accepted, and null is a valid 'unset'", ok.success);

  // The helpers the admin converts with, checked against their own contract.
  const tagsSrc = ADMIN.slice(ADMIN.indexOf("function tags("), ADMIN.indexOf("function csv("));
  check("empty tag input becomes null, not []", tagsSrc.includes("out.length ? out : null"));
  check("tags are trimmed and blanks dropped", tagsSrc.includes(".trim()") && tagsSrc.includes(".filter(Boolean)"));
}

console.log(`\n${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
