/**
 * Does every field in the admin actually reach the database?
 *
 * This is the oldest complaint about this back office and the most expensive
 * one to find by hand: a box you can type into that saves nothing. It has no
 * symptom at save time. The request returns 200, the dialog closes, the toast
 * says saved — and the value is simply gone when you reopen the record. The
 * only way anyone ever caught it was doing exactly what should never be
 * necessary: filling in a form, then going to the database to check.
 *
 * There are three links in the chain and a break in any one of them looks
 * identical from the outside:
 *
 *   1. the form field the author types into
 *   2. the zod schema the route parses the request body with
 *   3. the column in Postgres
 *
 * A field in (1) missing from (2) is stripped by `.parse()` and never reaches
 * the insert. A field in (3) missing from (1) can't be authored at all — and
 * worse, if the form writes the record without it, an edit-and-save blanks
 * whatever was there. TypeScript catches none of this: every layer is
 * internally consistent, they just disagree with each other.
 *
 * So this walks the actual dialog source for `form.x` reads, the actual zod
 * schema for its keys, and the actual Drizzle table for its columns, and
 * requires the three to agree. Anything deliberately not authored has to be
 * named in EXEMPT with a reason, which turns "I forgot" into "I decided".
 *
 * Run: tsx script/test-admin-fields.ts
 */

import { readFileSync } from "node:fs";
import { getTableColumns } from "drizzle-orm";
import {
  wellnessRoutines,
  routineHabits,
  insertWellnessRoutineSchema,
  insertRoutineHabitSchema,
  exercises,
  habitExercises,
  ebooks,
  energyCentres,
  frequencies,
  hosts,
} from "../shared/schema.js";

let passed = 0;
let failed = 0;

function check(name: string, cond: boolean, detail?: string) {
  if (cond) {
    passed++;
  } else {
    failed++;
    console.log(`  ✗ ${name}${detail ? ` — ${detail}` : ""}`);
  }
}

function section(title: string) {
  console.log(`\n${title}`);
}

const ADMIN = readFileSync("client/src/pages/AdminPortal.tsx", "utf8");

/**
 * Every `form.x` read inside one dialog function.
 *
 * Reading the source rather than a hand-kept list is the entire point: a list
 * of "fields the form has" is one more thing that can drift from the form,
 * and drift is the bug being tested for.
 */
function formFields(fnName: string): Set<string> {
  const start = ADMIN.indexOf(`function ${fnName}(`);
  if (start < 0) throw new Error(`${fnName} not found in AdminPortal.tsx`);

  // To the next top-level `function ` declaration, which is where this one ends.
  const after = ADMIN.indexOf("\nfunction ", start + 1);
  const body = ADMIN.slice(start, after < 0 ? undefined : after);

  const fields = new Set<string>();
  for (const m of body.matchAll(/\bform\.(\w+)/g)) fields.add(m[1]);
  // `set("x", …)` covers the write side, which for a checkbox or a Select is
  // the only place the name appears.
  for (const m of body.matchAll(/\bset\(\s*"(\w+)"/g)) fields.add(m[1]);
  return fields;
}

/**
 * Columns nobody authors in the dialog, and why. A column may only be here
 * for a reason that is true — "we forgot" is not one of them.
 */
const EXEMPT: Record<string, Record<string, string>> = {
  wellness_routines: {
    id: "slug, derived from the name by the server on create",
    createdAt: "set by the database",
    updatedAt: "set by the server on write",
    copyBlockId: "reserved for an external CMS reference; nothing reads it yet",
  },
  routine_habits: {
    id: "generated by the database",
    createdAt: "set by the database",
    updatedAt: "set by the server on write",
    copyBlockId: "reserved for an external CMS reference; nothing reads it yet",
    isFree: "gating lives on the routine's tier, not per habit",
    description: "legacy duplicate of shortDescription; kept for old rows only",
    intensity:
      "deliberately no longer asked for — nothing downstream serves a lite " +
      "vs intense variant, so it was a required choice with no consequence. " +
      "Column stays NOT NULL DEFAULT 'lite' so inserts are unaffected.",
  },
};

console.log("Admin fields reach the database");

const SUBJECTS = [
  {
    label: "Routine",
    table: wellnessRoutines,
    tableName: "wellness_routines",
    schema: insertWellnessRoutineSchema,
    dialog: "RoutineFormDialog",
  },
  {
    label: "Habit",
    table: routineHabits,
    tableName: "routine_habits",
    schema: insertRoutineHabitSchema,
    dialog: "HabitFormDialog",
  },
] as const;

for (const s of SUBJECTS) {
  section(`${s.label} — ${s.dialog} ↔ ${s.tableName}`);

  const columns = new Set(Object.keys(getTableColumns(s.table)));
  const schemaKeys = new Set(Object.keys(s.schema.shape));
  const fields = formFields(s.dialog);
  const exempt = EXEMPT[s.tableName] ?? {};

  // ── Link 1 → 2. A field the schema doesn't know is silently dropped by
  // .parse(), which is the quietest way to lose a value in the whole stack.
  const notInSchema = [...fields].filter((f) => !schemaKeys.has(f));
  check(
    `every form field survives ${s.label.toLowerCase()} validation`,
    notInSchema.length === 0,
    notInSchema.length ? `dropped by .parse(): ${notInSchema.join(", ")}` : "",
  );

  // ── Link 2 → 3. drizzle-zod derives the schema from the table, so a
  // mismatch here means someone hand-edited one of them.
  const schemaNotColumn = [...schemaKeys].filter((k) => !columns.has(k));
  check(
    `every ${s.label.toLowerCase()} schema key is a real column`,
    schemaNotColumn.length === 0,
    schemaNotColumn.join(", "),
  );

  // ── Link 3 → 1. A column with no field can't be authored, and a form that
  // writes the whole row without it blanks it on the next edit-and-save.
  const unauthored = [...columns].filter((c) => !fields.has(c) && !exempt[c]);
  check(
    `every ${s.label.toLowerCase()} column is either editable or explicitly exempt`,
    unauthored.length === 0,
    unauthored.length ? `no field for: ${unauthored.join(", ")}` : "",
  );

  // An exemption for a column that no longer exists is a stale note that will
  // outlive its reason and quietly excuse a future column of the same name.
  const staleExempt = Object.keys(exempt).filter((c) => !columns.has(c));
  check(`no stale exemptions for ${s.tableName}`, staleExempt.length === 0, staleExempt.join(", "));

  // An exemption for a field the form *does* have means the note is wrong
  // about the form, and the reason it gives is no longer being relied on.
  const contradicted = Object.keys(exempt).filter((c) => fields.has(c));
  check(
    `no exemption contradicts the ${s.dialog}`,
    contradicted.length === 0,
    contradicted.join(", "),
  );

  console.log(
    `  ${fields.size} fields, ${columns.size} columns, ${Object.keys(exempt).length} exempt`,
  );
}

/* ── The specific fields the old back office had ─────────────────────────── */

section("Parity with the previous admin");

{
  const routineFields = formFields("RoutineFormDialog");
  const habitFields = formFields("HabitFormDialog");

  // Everything the screenshots of the old Manage Routines / Manage Habits
  // forms could set. Listed explicitly because "the schema and the form
  // agree" is satisfied perfectly well by both of them being incomplete.
  const OLD_ROUTINE = [
    "name", "coverImageUrl", "description", "goal", "whoIsThisFor",
    "whatToExpect", "expectedResults", "goalDescription", "searchKeywords",
    "sortOrder", "isFeatured", "durationDays", "category", "icon", "color",
    "terrainTags",
  ];
  const OLD_HABIT = [
    "title", "routineId", "shortDescription", "detailedDescription",
    "scienceExplanation", "tips", "expectToNotice", "cadence",
    "durationMinutes", "icon", "recommendedTime", "dayStart", "dayEnd",
    "orderIndex", "terrainTags", "searchKeywords",
  ];

  const missingR = OLD_ROUTINE.filter((f) => f !== "routineId" && !routineFields.has(f));
  check("the routine form has everything the old one had", missingR.length === 0, missingR.join(", "));

  // routineId is set by the picker outside `form.` reads, so check the source
  // for the control itself rather than the form state.
  const missingH = OLD_HABIT.filter((f) => f !== "routineId" && !habitFields.has(f));
  check("the habit form has everything the old one had", missingH.length === 0, missingH.join(", "));
  check("the habit form still has the routine picker", ADMIN.includes('set("routineId"'));

  // The one thing deliberately dropped, and the meal-relative times added.
  check("intensity is no longer asked for", !habitFields.has("intensity"));
  check("recommended time offers pre-meal", ADMIN.includes('value="Pre-meal"'));
  check("recommended time offers post-meal", ADMIN.includes('value="Post-meal"'));
}

/* ── The tag columns are arrays, and the form holds text ─────────────────── */

section("Tag conversion");

{
  // text[] columns fed from comma-separated inputs. Sending the raw string
  // fails validation; sending [] would overwrite real tags with "none set".
  const parsedR = insertWellnessRoutineSchema.safeParse({
    id: "x", name: "n", description: "d", category: "Sleep",
    terrainTags: "sleep, gut",
  });
  check("a raw string is rejected for a text[] column", !parsedR.success);

  const ok = insertWellnessRoutineSchema.safeParse({
    id: "x", name: "n", description: "d", category: "Sleep",
    terrainTags: ["sleep", "gut"], searchKeywords: null,
  });
  check("an array is accepted, and null is a valid 'unset'", ok.success);

  // The helpers the admin converts with, checked against their own contract.
  const tagsSrc = ADMIN.slice(ADMIN.indexOf("function tags("), ADMIN.indexOf("function csv("));
  check("empty tag input becomes null, not []", tagsSrc.includes("out.length ? out : null"));
  check("tags are trimmed and blanks dropped", tagsSrc.includes(".trim()") && tagsSrc.includes(".filter(Boolean)"));
}

/* ── Build: the movement catalogue and the prescription ──────────────────── */

section("Build — Training.tsx ↔ exercises / habit_exercises");

{
  const TRAINING = readFileSync("client/src/components/admin/Training.tsx", "utf8");

  /**
   * The Build admin saves field-at-a-time rather than through a form object —
   * every write is `save.mutate({ id, body: { field: value } })`. So the set of
   * fields it can actually persist is the set of keys appearing in a `body`,
   * which is what this reads. Same principle as the dialogs above: ask the
   * source what it does, don't keep a list beside it and hope.
   */
  function writableFields(src: string): Set<string> {
    const out = new Set<string>();
    for (const m of src.matchAll(/body:\s*\{\s*(\w+)/g)) out.add(m[1]);
    // The create form posts a whole draft object instead.
    for (const m of src.matchAll(/draft,?\s*\n?\s*(\w+):/g)) out.add(m[1]);
    // And some writes skip the `body` wrapper and pass the payload straight to
    // apiRequest — the reorder does. Missing this pattern made the extractor
    // report orderIndex as uneditable while the reorder buttons were sitting
    // right there, which is the extractor lying rather than the admin.
    for (const call of src.matchAll(/apiRequest\(\s*"(?:PUT|POST|PATCH)"[^,]*,[^,]*,\s*\{([\s\S]{0,400}?)\n\s*\}\)/g)) {
      for (const k of call[1].matchAll(/^\s*(\w+):/gm)) out.add(k[1]);
    }
    return out;
  }

  const writable = writableFields(TRAINING);
  // The create draft, which is a different code path from the row editor.
  const draftMatch = TRAINING.match(/useState\(\{ name: "".*?\}\)/s);
  for (const m of (draftMatch?.[0] ?? "").matchAll(/(\w+):/g)) writable.add(m[1]);

  const exCols = new Set(Object.keys(getTableColumns(exercises)));
  const hxCols = new Set(Object.keys(getTableColumns(habitExercises)));

  const EX_EXEMPT: Record<string, string> = {
    id: "slug, generated from the name on create",
    createdAt: "set by the database",
    sortOrder: "unused — the catalogue is listed by name, not by a manual order",
  };
  const HX_EXEMPT: Record<string, string> = {
    id: "generated by the database",
    createdAt: "set by the database",
    routineHabitId: "the habit being edited; it is the route parameter, not a field",
    exerciseId: "chosen by the add-a-lift picker, which posts it on create",
  };

  const exMissing = [...exCols].filter((c) => !writable.has(c) && !EX_EXEMPT[c]);
  check(
    "every exercise column is editable or explicitly exempt",
    exMissing.length === 0,
    exMissing.length ? `no editor for: ${exMissing.join(", ")}` : "",
  );

  const hxMissing = [...hxCols].filter((c) => !writable.has(c) && !HX_EXEMPT[c]);
  check(
    "every prescription column is editable or explicitly exempt",
    hxMissing.length === 0,
    hxMissing.length ? `no editor for: ${hxMissing.join(", ")}` : "",
  );

  const staleEx = Object.keys(EX_EXEMPT).filter((c) => !exCols.has(c));
  const staleHx = Object.keys(HX_EXEMPT).filter((c) => !hxCols.has(c));
  check("no stale exercise exemptions", staleEx.length === 0, staleEx.join(", "));
  check("no stale prescription exemptions", staleHx.length === 0, staleHx.join(", "));

  // The specific ones that were unreachable, named so a regression is obvious
  // rather than showing up as a count.
  for (const f of ["muscleGroups", "demoUrl", "cues", "pattern", "equipment", "trackingType"]) {
    check(`exercise "${f}" can be edited after creation`, writable.has(f));
  }
  check('prescription "restSeconds" can be set', writable.has("restSeconds"));
  check('prescription "orderIndex" can be changed', writable.has("orderIndex"));

  // The reorder controls, which replaced a grip handle that was wired to
  // nothing at all.
  check("lifts can be moved up", TRAINING.includes("button-lift-up-"));
  check("lifts can be moved down", TRAINING.includes("button-lift-down-"));
  check(
    "the decorative drag handle is gone",
    !TRAINING.includes("GripVertical"),
    "a handle that looks draggable and isn't is worse than no handle",
  );

  console.log(`  ${writable.size} writable fields, ${exCols.size} + ${hxCols.size} columns`);
}

/* ── The library ─────────────────────────────────────────────────────────── */

section("Library — Library.tsx ↔ ebooks");

{
  const LIB = readFileSync("client/src/components/admin/Library.tsx", "utf8");

  const writable = new Set<string>();
  for (const m of LIB.matchAll(/body:\s*\{\s*(\w+)/g)) writable.add(m[1]);
  for (const m of LIB.matchAll(/\bdraft\.(\w+)/g)) writable.add(m[1]);
  for (const m of LIB.matchAll(/setDraft\(\{\s*\.\.\.draft,\s*(\w+)/g)) writable.add(m[1]);
  for (const call of LIB.matchAll(/apiRequest\(\s*"(?:PUT|POST|PATCH)"[^,]*,[^,]*,\s*\{([\s\S]{0,400}?)\n\s*\}\)/g)) {
    for (const k of call[1].matchAll(/^\s*(\w+):/gm)) writable.add(k[1]);
  }
  // The create draft object.
  const empty = LIB.match(/const EMPTY = \{[\s\S]*?\n\};/);
  for (const k of (empty?.[0] ?? "").matchAll(/^\s*(\w+):/gm)) writable.add(k[1]);

  const cols = new Set(Object.keys(getTableColumns(ebooks)));

  const EXEMPT: Record<string, string> = {
    id: "generated by the database",
    createdAt: "set by the database",
    updatedAt: "set by the server on write",
  };

  const missing = [...cols].filter((c) => !writable.has(c) && !EXEMPT[c]);
  check(
    "every ebook column is editable or explicitly exempt",
    missing.length === 0,
    missing.length ? `no editor for: ${missing.join(", ")}` : "",
  );

  const stale = Object.keys(EXEMPT).filter((c) => !cols.has(c));
  check("no stale ebook exemptions", stale.length === 0, stale.join(", "));

  // The old admin's eBook form, field by field.
  for (const f of [
    "coverUrl", "title", "slug", "author", "subtitle", "publishedAt",
    "priceCents", "description", "sortOrder", "category", "fileUrl",
    "audioUrl", "promoVideoUrl", "unlocksCommunity", "isPublished", "routineId",
  ]) {
    check(`ebook "${f}" can be authored`, writable.has(f));
  }

  console.log(`  ${writable.size} writable fields, ${cols.size} columns`);
}

/* ── The Body ────────────────────────────────────────────────────────────── */

section("The Body — Energy.tsx ↔ energy_centres / frequencies");

{
  const EN = readFileSync("client/src/components/admin/Energy.tsx", "utf8");

  const writable = new Set<string>();
  for (const m of EN.matchAll(/body:\s*\{\s*(\w+)/g)) writable.add(m[1]);
  for (const m of EN.matchAll(/setDraft\(\{\s*\.\.\.draft,\s*(\w+)/g)) writable.add(m[1]);
  for (const m of EN.matchAll(/useState\(\{([^}]*)\}\)/g)) {
    for (const k of m[1].matchAll(/(\w+):/g)) writable.add(k[1]);
  }

  const centreCols = new Set(Object.keys(getTableColumns(energyCentres)));
  const freqCols = new Set(Object.keys(getTableColumns(frequencies)));

  const CENTRE_EXEMPT: Record<string, string> = {
    id: "slug, typed on create and permanent afterwards",
    createdAt: "set by the database",
    updatedAt: "set by the server on write",
  };
  const FREQ_EXEMPT: Record<string, string> = {
    id: "generated by the database",
    createdAt: "set by the database",
  };

  const cMissing = [...centreCols].filter((c) => !writable.has(c) && !CENTRE_EXEMPT[c]);
  check("every centre column is editable or exempt", cMissing.length === 0, cMissing.join(", "));

  const fMissing = [...freqCols].filter((c) => !writable.has(c) && !FREQ_EXEMPT[c]);
  check("every frequency column is editable or exempt", fMissing.length === 0, fMissing.join(", "));

  // A centre has is_published and a frequency has is_active. They are not the
  // same column and the hand-written type had the wrong one on the centre.
  check("a centre can be unpublished", writable.has("isPublished"));
  check("a frequency can be switched off", writable.has("isActive"));
  check(
    "nothing writes isActive to a centre",
    !/energy\/centres[\s\S]{0,2000}?isActive/.test(EN),
    "energy_centres has no is_active column — that write would be dropped",
  );

  console.log(`  ${writable.size} writable fields, ${centreCols.size} + ${freqCols.size} columns`);
}

/* ── No hand-written copies of a table anywhere in the admin ─────────────── */

section("Client types derive from the schema");

{
  // The mechanism behind every "it didn't save" in this back office: a client
  // interface restating a table's columns. It drifts silently in both
  // directions and TypeScript is satisfied throughout, because the lie is
  // internally consistent. These files must derive instead.
  const FILES = [
    "client/src/hooks/use-coaching.ts",
    "client/src/components/admin/Training.tsx",
    "client/src/components/admin/Library.tsx",
    "client/src/components/admin/Energy.tsx",
  ];
  for (const f of FILES) {
    const src = readFileSync(f, "utf8");
    check(`${f} imports its row types from the schema`, src.includes('from "@shared/schema"'));
    check(
      `${f} has no hand-written WellnessRoutine/Exercise interface`,
      !/interface\s+(WellnessRoutine|RoutineHabitTemplate|Exercise|Prescribed|Ebook|Section|Centre|Frequency)\b/.test(src),
    );
  }
}


// ── HOSTS ──────────────────────────────────────────────────────────────────
//
// Hosts are edited in their own component rather than an AdminPortal dialog,
// so the extractor above does not reach them. The check is the same one: the
// Draft interface is the ceiling on what a host can be given, and a column
// missing from it cannot be set from anywhere but SQL.
section("Host — Hosts.tsx Draft ↔ hosts");

const HOSTS_SRC = readFileSync("client/src/components/admin/Hosts.tsx", "utf8");
const draftBlock = /interface Draft \{([\s\S]*?)\n\}/.exec(HOSTS_SRC)?.[1] ?? "";
const draftFields = new Set(
  Array.from(draftBlock.matchAll(/^\s*(\w+)\s*[?:]/gm)).map((m) => m[1])
);

const HOST_EXEMPT: Record<string, string> = {
  id: "generated by the database",
  createdAt: "set by the database",
  userId:
    "dormant. The column links a host to a member account, and as of this " +
    "commit nothing writes it and nothing reads it — server/offerings/routes.ts " +
    "joins hosts by id only. Wiring a picker would add a control whose value " +
    "changes nothing observable. If a feature ever consumes it, this exemption " +
    "is the note that says an editor has to come with it.",
};

const hostColumns = new Set(Object.keys(getTableColumns(hosts)));
const hostMissing = Array.from(hostColumns).filter(
  (c) => !draftFields.has(c) && !HOST_EXEMPT[c]
);
check(
  "every host column is editable or explicitly exempt",
  hostMissing.length === 0,
  hostMissing.join(", ")
);

const staleHost = Object.keys(HOST_EXEMPT).filter((c) => !hostColumns.has(c));
check("no stale host exemptions", staleHost.length === 0, staleHost.join(", "));

const contradictedHost = Object.keys(HOST_EXEMPT).filter((c) => draftFields.has(c));
check("no host exemption contradicts the form", contradictedHost.length === 0, contradictedHost.join(", "));

/**
 * The exemption above is only honest while it stays true. If a reader appears,
 * the column stops being dormant and the note becomes a excuse rather than a
 * decision.
 */
const OFFERINGS_ROUTES = readFileSync("server/offerings/routes.ts", "utf8");
check(
  "hosts.userId is still genuinely unread",
  !/hosts\.userId/.test(OFFERINGS_ROUTES),
  "something now reads hosts.userId — it needs an editor, not an exemption"
);


console.log(`\n${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
